"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { AlertCircle, ArrowRight, Loader2 } from "lucide-react";

type Row = Record<string, unknown>;
function s(value: unknown) { return value == null ? "" : String(value); }
function arr(value: unknown) { return Array.isArray(value) ? value as Row[] : []; }

export function DiagnosticsCentre() { const [rows, setRows] = useState<Row[]>([]); const [selected, setSelected] = useState<Row | null>(null); const [loading, setLoading] = useState(true); useEffect(() => { void fetch("/api/timetable/history", { cache: "no-store" }).then((response) => response.json()).then((body) => setRows(body.data ?? [])).finally(() => setLoading(false)); }, []); if (loading) return <div className="p-12 text-center text-sm text-slate-400"><Loader2 className="mx-auto mb-2 h-5 w-5 animate-spin" />Loading diagnostics…</div>; return <div className="space-y-6"><div><p className="mb-2 text-sm font-semibold text-teal">TIMETABLE WORKSPACE</p><h1 className="text-3xl font-bold tracking-tight text-navy">Conflict & diagnostics centre</h1><p className="mt-2 text-sm text-slate-500">Choose a generation to inspect unscheduled courses, rejected slots, and hard validation violations.</p></div><section className="rounded-xl border border-slate-200 bg-white p-5 shadow-card"><label className="text-sm font-semibold text-slate-700">Generation<select value={s(selected?.id)} onChange={(event) => setSelected(rows.find((row) => s(row.id) === event.target.value) ?? null)} className="mt-2 h-10 w-full max-w-xl rounded-lg border border-slate-200 bg-white px-3 font-normal"><option value="">Select a generation</option>{rows.map((row) => <option key={s(row.id)} value={s(row.id)}>{s((row.period as Row)?.name)} · {new Date(s(row.generatedAt)).toLocaleString()}</option>)}</select></label>{selected && <Link href={`/timetable/generations/${s(selected.id)}`} className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-teal">Open diagnostics in review workspace <ArrowRight className="h-4 w-4" /></Link>}</section>{!selected && <div className="rounded-xl border border-dashed border-slate-300 bg-white p-12 text-center text-sm text-slate-500">No generation selected.</div>}{selected && <div className="flex items-start gap-3 rounded-xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-800"><AlertCircle className="mt-0.5 h-5 w-5 shrink-0" />The review workspace provides structured diagnostics and candidate-slot rejection details for this generation.</div>}</div>; }
