import { requireResourceManager, requireResourceRead } from "@/server/resources/access";
import { availabilityInput, venueInput } from "@/server/resources/schemas";
import { addVenueUnavailable, getVenue, removeVenueUnavailable, updateVenue, updateVenueUnavailable } from "@/server/resources/services";
import { resourceError, resourceSuccess, resourceValidation } from "@/server/resources/http";

export async function GET(_request: Request, { params }: { params: Promise<{ id: string }> }) { try { await requireResourceRead(); return resourceSuccess(await getVenue((await params).id)); } catch (error) { return resourceError(error); } }
export async function PUT(request: Request, { params }: { params: Promise<{ id: string }> }) { try { const session = await requireResourceManager(); const parsed = venueInput.safeParse(await request.json()); if (!parsed.success) return resourceValidation("Check the venue details.", parsed.error.flatten()); return resourceSuccess(await updateVenue((await params).id, parsed.data, session.user.id)); } catch (error) { return resourceError(error); } }
export async function POST(request: Request, { params }: { params: Promise<{ id: string }> }) { try { const session = await requireResourceManager(); const parsed = availabilityInput.safeParse(await request.json()); if (!parsed.success) return resourceValidation("Check the unavailable period.", parsed.error.flatten()); return resourceSuccess(await addVenueUnavailable((await params).id, parsed.data, session.user.id), 201); } catch (error) { return resourceError(error); } }
export async function PATCH(request: Request) { try { const session = await requireResourceManager(); const availabilityId = new URL(request.url).searchParams.get("availabilityId"); if (!availabilityId) return resourceValidation("availabilityId is required."); const parsed = availabilityInput.safeParse(await request.json()); if (!parsed.success) return resourceValidation("Check the unavailable period.", parsed.error.flatten()); return resourceSuccess(await updateVenueUnavailable(availabilityId, parsed.data, session.user.id)); } catch (error) { return resourceError(error); } }
export async function DELETE(request: Request) { try { const session = await requireResourceManager(); const id = new URL(request.url).searchParams.get("availabilityId"); if (!id) return resourceValidation("availabilityId is required."); return resourceSuccess(await removeVenueUnavailable(id, session.user.id)); } catch (error) { return resourceError(error); } }
