import Link from "next/link";
import { getPublishedTimetable } from "@/server/timetable/public-service";
import { filterTimetableRows,type TimetableFilters } from "@/domain/timetable/public-data";
import { PrintTimetableButton } from "@/components/timetable/print-button";

export const dynamic="force-dynamic";
export default async function PublicTimetablePage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}) {
  const query=await searchParams;const filters:TimetableFilters=Object.fromEntries(["programme","level","course","date","venue","mode"].map((key)=>[key,typeof query[key]==="string"?query[key]:undefined]));
  const data=await getPublishedTimetable(typeof query.revisionId==="string"?query.revisionId:undefined);
  if(!data)return <main className="mx-auto max-w-5xl p-8"><h1 className="text-3xl font-bold">BOUESTI Examination Timetable</h1><p className="mt-5">No published timetable is currently available.</p></main>;
  const rows=filterTimetableRows(data.rows,filters),programmes=[...new Map(data.rows.flatMap((r)=>r.programmes).map((p)=>[p.id,p])).values()],venues=[...new Map(data.rows.map((r)=>[r.venueId,r.venue])).entries()];
  const exportQuery=new URLSearchParams({revisionId:data.revisionId,...Object.fromEntries(Object.entries(filters).filter((entry):entry is [string,string]=>Boolean(entry[1])))});
  const field="rounded border border-slate-300 bg-white px-3 py-2";
  return <main className="mx-auto max-w-7xl space-y-6 p-5 md:p-10"><header><p className="font-bold text-teal">BAMIDELE OLUMILUA UNIVERSITY OF EDUCATION, SCIENCE AND TECHNOLOGY, IKERE-EKITI</p><h1 className="mt-3 text-3xl font-bold text-navy">Examination Timetable</h1><p className="mt-3">{data.session} · {data.semester} · {data.period}</p><p className="text-sm text-slate-600">Published revision {data.revisionNumber} · {data.publishedAt?.slice(0,10)}</p></header>
    <form className="grid gap-3 rounded-xl border bg-slate-50 p-4 sm:grid-cols-3 print:hidden"><input type="hidden" name="revisionId" value={data.revisionId}/><label>Programme<select name="programme" className={`${field} block w-full`} defaultValue={filters.programme??""}><option value="">All programmes</option>{programmes.map((p)=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Level<input name="level" type="number" className={`${field} block w-full`} defaultValue={filters.level}/></label><label>Course code<input name="course" className={`${field} block w-full`} defaultValue={filters.course}/></label><label>Date<input name="date" type="date" className={`${field} block w-full`} defaultValue={filters.date}/></label><label>Venue<select name="venue" className={`${field} block w-full`} defaultValue={filters.venue??""}><option value="">All venues</option>{venues.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>Mode<select name="mode" className={`${field} block w-full`} defaultValue={filters.mode??""}><option value="">All modes</option><option value="CBT">CBT</option><option value="PEN_ON_PAPER">Written</option></select></label><button className="rounded bg-navy px-4 py-2 font-semibold text-white">Apply filters</button><Link href="/public/timetable" className="p-2 text-teal">Clear filters</Link></form>
    <div className="flex flex-wrap gap-5 text-sm font-semibold text-teal print:hidden"><PrintTimetableButton/><a href={`/api/timetable/export?${exportQuery}&format=pdf`}>Download PDF</a><a href={`/api/timetable/export?${exportQuery}&format=xlsx`}>Download Excel</a></div>
    <div className="overflow-x-auto"><table className="w-full border-collapse text-left text-sm"><thead className="bg-slate-100"><tr>{["Date","Time","Course","Programme / Level","Mode","Venue","Candidates","Batch"].map((label)=><th key={label} className="border p-3">{label}</th>)}</tr></thead><tbody>{rows.map((r,index)=><tr key={index}><td className="border p-3">{r.date}</td><td className="border p-3">{r.startTime}–{r.endTime}</td><td className="border p-3"><strong>{r.courseCode}</strong><div>{r.courseTitle}</div></td><td className="border p-3">{r.programmes.map((p)=>`${p.name} / ${p.level}`).join("; ")}</td><td className="border p-3">{r.mode==="CBT"?"CBT":"Written"}</td><td className="border p-3">{r.venue}</td><td className="border p-3">{r.candidateCount}</td><td className="border p-3">{r.batch??"—"}</td></tr>)}</tbody></table>{!rows.length&&<p className="p-6">No examinations match your filters.</p>}</div>
  </main>;
}
