import { describe, expect, it } from "vitest";
import { buildConflictGraph, type ExamEvent } from "@/domain/exams";
import { generateCbtBatchedAggregateTimetable, calculateRequiredBatches, splitCandidateCounts, previewCbtBatches, validateCbtSittings, validateCompleteAggregateTimetable, type AggregateSchedulingDataset, type CbtSitting, type SchedulingExamEvent } from "@/domain/timetable";
import { resolveAggregateGenerationConfig } from "@/domain/timetable";
import { cbtSittingPersistenceData, createAggregateGenerationSnapshot } from "@/server/timetable/aggregate-generation-service";

function cbtEvent(id: string, candidateCount: number): SchedulingExamEvent { return { id, title: id, memberCourseCodes: [id], candidateCount, cohortKeys: [`cohort-${id}`], examMode: "CBT", durationMinutes: 60, source: "AUTO_AGGREGATED", offeringIds: [id] }; }
function paperEvent(id: string): SchedulingExamEvent { return { id, title: id, memberCourseCodes: [id], candidateCount: 50, cohortKeys: [`cohort-${id}`], examMode: "PEN_ON_PAPER", durationMinutes: 60, source: "AUTO_AGGREGATED", offeringIds: [id] }; }
function dataset(events: SchedulingExamEvent[], enabled = true): AggregateSchedulingDataset {
  const graphEvents = events.map((item) => ({ id: item.id, title: item.title, memberOfferings: [], courseCodes: item.memberCourseCodes, canonicalCourseKeys: item.memberCourseCodes, candidateCount: item.candidateCount, cohortKeys: item.cohortKeys, examMode: item.examMode, durationMinutes: item.durationMinutes, source: item.source } as unknown as ExamEvent));
  return { session: { id: "s", name: "Session", active: true }, semester: { id: "sem", sessionId: "s", name: "Semester", active: true }, examPeriod: { id: "p", sessionId: "s", semesterId: "sem", name: "Period", startDate: "2026-01-01", endDate: "2026-01-31", active: true }, events, timeSlots: [{ id: "slot-1", examPeriodId: "p", date: "2026-01-05", startTime: "08:00", endTime: "09:00" }, { id: "slot-2", examPeriodId: "p", date: "2026-01-05", startTime: "09:30", endTime: "10:30" }, { id: "slot-3", examPeriodId: "p", date: "2026-01-06", startTime: "08:00", endTime: "09:00" }], calendarDays: [{ examPeriodId: "p", date: "2026-01-05", enabled: true, dayType: "WEEKDAY", startTime: "08:00", endTime: "18:00" }, { examPeriodId: "p", date: "2026-01-06", enabled: true, dayType: "WEEKDAY", startTime: "08:00", endTime: "18:00" }], timePolicy: { defaultDayStartTime: "08:00", defaultDayEndTime: "18:00", defaultTurnaroundMinutes: 30, writtenTurnaroundMinutes: 30, cbtTurnaroundMinutes: 30, timeGranularityMinutes: 30 }, schedulingMode: "FLEXIBLE_INTERVALS", conflictGraph: buildConflictGraph(graphEvents), venues: [{ id: "u", code: "UCRC", name: "UCRC", capacity: 300, usableComputerCapacity: 250, capability: "CBT", active: true }, { id: "l", code: "LIB", name: "Library ICT", capacity: 120, usableComputerCapacity: 100, capability: "CBT", active: true }], venueUnavailability: [], invigilators: [{ id: "i1", staffId: "I1", name: "Invigilator 1", active: true, maximumDailyAssignments: 10, role: "INVIGILATOR" }, { id: "i2", staffId: "I2", name: "Invigilator 2", active: true, maximumDailyAssignments: 10, role: "INVIGILATOR" }, { id: "t1", staffId: "T1", name: "Support 1", active: true, maximumDailyAssignments: 10, role: "CBT_TECHNICAL_SUPPORT" }, { id: "t2", staffId: "T2", name: "Support 2", active: true, maximumDailyAssignments: 10, role: "CBT_TECHNICAL_SUPPORT" }], invigilatorUnavailability: [], cbtBatchingPolicy: { enabled, minimumBatchGapMinutes: 30, maxBatchesPerDay: null, requireSameDay: true, allowMultiDay: false, preferMaximumCapacityPerBatch: true }, cbtStaffingPolicy: { minimumInvigilatorsPerVenue: 1, minimumTechnicalSupportPerVenue: 1 }, config: resolveAggregateGenerationConfig({ maxGenerationAttempts: 1, seed: 2 }) };
}

function validSitting(eventId: string, candidateCount: number, overrides: Partial<CbtSitting> = {}): CbtSitting {
  return { eventId, sequenceNumber: 1, batchLabel: "A", candidateCount, date: "2026-01-05", startTime: "08:00", endTime: "09:00", venues: [{ venueId: "u", allocatedCandidates: candidateCount, allocatedCapacity: 250 }], staff: [{ staffId: "i1", assignmentType: "INVIGILATOR", venueId: "u" }, { staffId: "t1", assignmentType: "TECHNICAL_SUPPORT", venueId: "u" }], ...overrides };
}

describe("CBT batching", () => {
  it("calculates deterministic batch sizes at capacity boundaries", () => { expect(calculateRequiredBatches(100, 350)).toBe(1); expect(calculateRequiredBatches(350, 350)).toBe(1); expect(calculateRequiredBatches(351, 350)).toBe(2); expect(calculateRequiredBatches(620, 350)).toBe(2); expect(calculateRequiredBatches(701, 350)).toBe(3); expect(splitCandidateCounts(620, 350)).toEqual([350, 270]); });
  it("allocates an oversized event across same-day sittings and both venues", () => { const input = dataset([cbtEvent("GST203", 620)]); expect(previewCbtBatches(input)[0]?.candidateCounts).toEqual([350, 270]); const result = generateCbtBatchedAggregateTimetable(input).candidate; expect(result.sittings).toHaveLength(2); expect(result.sittings?.map((item) => item.candidateCount)).toEqual([350, 270]); expect(result.sittings?.map((item) => item.sequenceNumber)).toEqual([1, 2]); expect(result.sittings?.[1]?.startTime).toBe("09:30"); expect(result.sittings?.reduce((sum, item) => sum + item.candidateCount, 0)).toBe(620); expect(result.sittings?.[0]?.venues.map((item) => item.allocatedCandidates)).toEqual([250, 100]); expect(result.sittings?.[1]?.venues.reduce((sum, item) => sum + item.allocatedCandidates, 0)).toBe(270); expect(validateCbtSittings(result.sittings ?? [], input)).toEqual([]); });
  it("supports fixed CBT sessions", () => { const input = { ...dataset([cbtEvent("FIXED", 620)]), schedulingMode: "FIXED_SESSIONS" as const }; const result = generateCbtBatchedAggregateTimetable(input).candidate; expect(result.sittings).toHaveLength(2); expect(result.sittings?.map((item) => item.startTime)).toEqual(["08:00", "09:30"]); expect(validateCbtSittings(result.sittings ?? [], input)).toEqual([]); });
  it("supports flexible CBT sessions within the daily window", () => { const input = dataset([cbtEvent("FLEX", 620)]); const result = generateCbtBatchedAggregateTimetable(input).candidate; expect(result.sittings?.every((item) => item.endTime <= "18:00")).toBe(true); });
  it("blocks oversized CBT when batching is disabled and support is role-specific", () => { const input = dataset([cbtEvent("BIG", 420)], false); const result = generateCbtBatchedAggregateTimetable(input).candidate; expect(result.sittings).toHaveLength(0); expect(result.hardViolations.some((item) => item.code === "CBT_BATCHING_DISABLED_FOR_OVERSIZED_EVENT")).toBe(true); });
  it("does not treat an ordinary invigilator as technical support", () => { const input = dataset([cbtEvent("SMALL", 100)]); input.invigilators = [{ id: "i1", staffId: "I1", name: "Invigilator", active: true, maximumDailyAssignments: 10, role: "INVIGILATOR" }]; const result = generateCbtBatchedAggregateTimetable(input).candidate; expect(result.sittings).toHaveLength(0); expect(result.hardViolations.some((item) => item.code === "NO_FEASIBLE_CBT_BATCH_WINDOW")).toBe(true); });
});

describe("CBT sitting invariants", () => {
  it("accepts a valid sitting and rejects a batch total mismatch", () => { const input = dataset([cbtEvent("EVENT", 100)]); expect(validateCbtSittings([validSitting("EVENT", 100)], input)).toEqual([]); expect(validateCbtSittings([validSitting("EVENT", 90)], input).some((item) => item.code === "CBT_CANDIDATE_COUNT_MISMATCH")).toBe(true); });
  it("rejects zero-size batches and venue allocation mismatches", () => { const input = dataset([cbtEvent("EVENT", 100)]); const zero = validSitting("EVENT", 0, { venues: [{ venueId: "u", allocatedCandidates: 0, allocatedCapacity: 250 }] }); const mismatch = validSitting("EVENT", 100, { venues: [{ venueId: "u", allocatedCandidates: 90, allocatedCapacity: 250 }] }); expect(validateCbtSittings([zero], input).some((item) => item.code === "INVALID_CBT_SITTING")).toBe(true); expect(validateCbtSittings([mismatch], input).some((item) => item.code === "CBT_CANDIDATE_COUNT_MISMATCH")).toBe(true); });
  it("rejects venue over-capacity", () => { const input = dataset([cbtEvent("EVENT", 251)]); const sitting = validSitting("EVENT", 251, { venues: [{ venueId: "u", allocatedCandidates: 251, allocatedCapacity: 251 }] }); expect(validateCbtSittings([sitting], input).some((item) => item.code === "INSUFFICIENT_CBT_CAPACITY")).toBe(true); });
  it("rejects overlap and insufficient batch gap", () => { const input = dataset([cbtEvent("EVENT", 100)]); const first = validSitting("EVENT", 50); const second = validSitting("EVENT", 50, { sequenceNumber: 2, batchLabel: "B", startTime: "08:30", endTime: "09:30" }); const gap = validSitting("EVENT", 50, { sequenceNumber: 2, batchLabel: "B", startTime: "09:15", endTime: "10:15", staff: [{ staffId: "i2", assignmentType: "INVIGILATOR", venueId: "u" }, { staffId: "t2", assignmentType: "TECHNICAL_SUPPORT", venueId: "u" }] }); expect(validateCbtSittings([first, second], input).some((item) => item.code === "CBT_SITTING_OVERLAP")).toBe(true); expect(validateCbtSittings([first, gap], input).some((item) => item.code === "CBT_BATCH_GAP")).toBe(true); });
  it("rejects invalid sequences, same-day violations, and missing technical support", () => { const input = dataset([cbtEvent("EVENT", 100)]); const invalidSequence = [validSitting("EVENT", 50), validSitting("EVENT", 50, { sequenceNumber: 3, batchLabel: "C", startTime: "09:30", endTime: "10:30", staff: [{ staffId: "i2", assignmentType: "INVIGILATOR", venueId: "u" }, { staffId: "t2", assignmentType: "TECHNICAL_SUPPORT", venueId: "u" }] })]; const differentDay = validSitting("EVENT", 50, { sequenceNumber: 2, batchLabel: "B", date: "2026-01-06", staff: [{ staffId: "i2", assignmentType: "INVIGILATOR", venueId: "u" }, { staffId: "t2", assignmentType: "TECHNICAL_SUPPORT", venueId: "u" }] }); expect(validateCbtSittings(invalidSequence, input).some((item) => item.code === "INVALID_CBT_SEQUENCE")).toBe(true); expect(validateCbtSittings([validSitting("EVENT", 50), differentDay], input).some((item) => item.code === "CBT_SAME_DAY_REQUIREMENT")).toBe(true); const missingSupport = validSitting("EVENT", 100, { staff: [{ staffId: "i1", assignmentType: "INVIGILATOR", venueId: "u" }] }); expect(validateCbtSittings([missingSupport], input).some((item) => item.code === "INSUFFICIENT_CBT_TECHNICAL_SUPPORT")).toBe(true); });
  it("maps sitting persistence fields without a redundant period key", () => { const mapped = cbtSittingPersistenceData(validSitting("EVENT", 100), "generation-1"); expect(mapped).toMatchObject({ generationId: "generation-1", examEventId: "EVENT", sequenceNumber: 1, candidateCount: 100, startTime: "08:00", endTime: "09:00" }); expect(mapped).not.toHaveProperty("examPeriodId"); });
  it("keeps generation snapshots deterministic and preserves the non-CBT path", () => { const input = dataset([paperEvent("PAPER")]); expect(generateCbtBatchedAggregateTimetable(input).candidate.sittings).toEqual([]); const first = createAggregateGenerationSnapshot(input); const second = createAggregateGenerationSnapshot(input); expect(first).toEqual(second); expect(first.schemaVersion).toBe("aggregate-event-fixed-slot-v1"); });
});

describe("CBT cross-event validation", () => {
  it("reserves venues and technical staff across separate CBT events", () => {
    const input = dataset([cbtEvent("A", 350), cbtEvent("B", 350)]);
    const result = generateCbtBatchedAggregateTimetable(input).candidate;
    expect(result.sittings).toHaveLength(2);
    expect(result.sittings?.map((s) => s.startTime)).toEqual(["08:00", "09:30"]);
    expect(validateCompleteAggregateTimetable(result, input).violations).toEqual([]);
  });
  it("rejects CBT outside the saved calendar and missing logical events", () => {
    const input = dataset([cbtEvent("A", 100)]);
    const result = generateCbtBatchedAggregateTimetable(input).candidate;
    result.sittings![0].date = "2026-02-01";
    expect(validateCompleteAggregateTimetable(result, input).valid).toBe(false);
    result.sittings = [];
    expect(validateCompleteAggregateTimetable(result, input).violations.some((v) => v.code === "UNSCHEDULED_EVENT")).toBe(true);
  });
  it("consumes the per-day CBT turnaround override", () => {
    const input = dataset([cbtEvent("A", 350), cbtEvent("B", 350)]);
    input.calendarDays![0].turnaroundMinutesOverride = 90;
    expect(generateCbtBatchedAggregateTimetable(input).candidate.sittings?.map((s) => s.startTime)).toEqual(["08:00", "10:30"]);
  });
});
