import { describe, expect, it } from "vitest";
import { exportValues, timetableExcel, timetablePdf } from "@/server/timetable/export-service";
import { filterTimetableRows, publicTimetableData } from "@/domain/timetable/public-data";
import type { AggregateSchedulingDataset, AggregateCandidateTimetable } from "@/domain/timetable";

const dataset = { session:{id:"s",name:"2025/2026",active:true}, semester:{id:"m",sessionId:"s",name:"First",active:true}, examPeriod:{id:"p",sessionId:"s",semesterId:"m",name:"Main",startDate:"2026-01-01",endDate:"2026-01-31",active:true}, events:[{id:"e",title:"GST 101",memberCourseCodes:["GST101"],candidateCount:100,cohortKeys:["prog:100"],examMode:"CBT",durationMinutes:60,source:"AUTO_AGGREGATED",offeringIds:["o"],members:[{programmeId:"prog",programmeName:"BSc",level:100,courseCode:"GST101",courseTitle:"GST 101"}]}],timeSlots:[],calendarDays:[],conflictGraph:{events:[],edges:[],metrics:{events:1,edges:0,density:0,hardEdges:0,softEdges:0}} as any,venues:[{id:"v",code:"ICT",name:"ICT Centre",capacity:120,usableComputerCapacity:120,capability:"CBT",active:true}],venueUnavailability:[],invigilators:[],invigilatorUnavailability:[],config:{} as any,schedulingMode:"FLEXIBLE_INTERVALS" as const } as AggregateSchedulingDataset;
const candidate = { assignments:[], sittings:[{eventId:"e",sequenceNumber:1,batchLabel:"A",candidateCount:100,date:"2026-01-05",startTime:"08:00",endTime:"09:00",venues:[{venueId:"v",allocatedCandidates:100,allocatedCapacity:120}],staff:[]}],unscheduledEvents:[],hardViolations:[],softScore:0,metrics:{} as any } as AggregateCandidateTimetable;

describe("public timetable and exports",()=>{
  it("whitelists timetable rows and preserves CBT batch fields",()=>{const data=publicTimetableData(candidate,dataset);expect(data.rows).toHaveLength(1);expect(data.rows[0]).toMatchObject({courseCode:"GST101",mode:"CBT",candidateCount:100,batch:1});expect(JSON.stringify(data)).not.toContain("student");expect(exportValues(data.rows[0])).toContain(1);});
  it("filters by programme, date, venue, and mode",()=>{const row=publicTimetableData(candidate,dataset).rows;expect(filterTimetableRows(row,{programme:"prog",level:"100",date:"2026-01-05",venue:"v",mode:"CBT"})).toHaveLength(1);expect(filterTimetableRows(row,{mode:"PEN_ON_PAPER"})).toHaveLength(0);});
  it("carries written shared and split seat allocations into both export formats", async()=>{const written={...dataset,events:[{...dataset.events[0],id:"a",title:"CSC301",memberCourseCodes:["CSC301"],candidateCount:120,examMode:"PEN_ON_PAPER" as const}],venues:[{id:"llt",code:"LLT1",name:"LLT1",capacity:300,examCapacity:300,capability:"WRITTEN" as const,active:true},{id:"nav",code:"NAVATES2",name:"Navates 2",capacity:160,examCapacity:160,capability:"WRITTEN" as const,active:true}]};const writtenCandidate={assignments:[{eventId:"a",timeSlotId:null,date:"2026-01-05",startTime:"08:00",endTime:"09:00",venues:[{venueId:"llt",allocatedCandidates:120,allocatedCapacity:300}],invigilators:[]}],sittings:[],unscheduledEvents:[],hardViolations:[],softScore:0,metrics:{}} as unknown as AggregateCandidateTimetable;const data={...publicTimetableData(writtenCandidate,written),revisionNumber:1,status:"COMPLETED",publishedAt:null};expect(data.rows[0]?.candidateCount).toBe(120);expect(exportValues(data.rows[0]!)).toContain(120);expect((await timetablePdf(data)).subarray(0,4).toString()).toBe("%PDF");const workbook=await timetableExcel(data);expect(workbook.subarray(0,2).toString("hex")).toBe("504b");});
});
