import { describe, expect, it } from "vitest";
import { buildConflictGraph, type ExamEvent } from "@/domain/exams";
import { assessPlannerFeasibility, generateCalendarProposal, monthRange, type PlannerDay } from "@/domain/timetable/planner";
import { intervalContains, intervalDuration, intervalsAdjacent, intervalsOverlap, makeInterval, minutesToTime, timeToMinutes } from "@/domain/timetable/intervals";
import { generateFlexibleAggregateTimetable, validateAggregateTimetable, type AggregateSchedulingDataset, type SchedulingExamEvent } from "@/domain/timetable";
import { resolveAggregateGenerationConfig } from "@/domain/timetable";

const policy = { defaultDayStartTime: "08:00", defaultDayEndTime: "18:00", defaultTurnaroundMinutes: 30, writtenTurnaroundMinutes: 30, cbtTurnaroundMinutes: 15, timeGranularityMinutes: 30, weekdays: [false, true, true, true, true, true, false] };
function event(id: string, durationMinutes = 180): SchedulingExamEvent { return { id, title: id, memberCourseCodes: [id], candidateCount: 50, cohortKeys: [`cohort-${id}`], examMode: "PEN_ON_PAPER", durationMinutes, source: "AUTO_AGGREGATED", offeringIds: [id] }; }
function dataset(events: SchedulingExamEvent[]): AggregateSchedulingDataset { const graphEvents = events.map((item) => ({ id: item.id, title: item.title, memberOfferings: [], courseCodes: item.memberCourseCodes, canonicalCourseKeys: item.memberCourseCodes, candidateCount: item.candidateCount, cohortKeys: item.cohortKeys, examMode: item.examMode, durationMinutes: item.durationMinutes, source: item.source } as unknown as ExamEvent)); return { session: { id: "s", name: "Session", active: true }, semester: { id: "sem", sessionId: "s", name: "Semester", active: true }, examPeriod: { id: "p", sessionId: "s", semesterId: "sem", name: "Period", startDate: "2026-01-01", endDate: "2026-01-31", active: true }, events, timeSlots: [], calendarDays: [{ examPeriodId: "p", date: "2026-01-05", enabled: true, dayType: "WEEKDAY", startTime: "08:00", endTime: "18:00" }], timePolicy: policy, schedulingMode: "FLEXIBLE_INTERVALS", conflictGraph: buildConflictGraph(graphEvents), venues: [{ id: "v", code: "V", name: "Hall", capacity: 100, examCapacity: 100, capability: "WRITTEN", active: true }], venueUnavailability: [], invigilators: [{ id: "i", staffId: "I", name: "Invigilator", active: true, maximumDailyAssignments: 10 }], invigilatorUnavailability: [], config: resolveAggregateGenerationConfig({ maxGenerationAttempts: 1, seed: 4 }) }; }

describe("Phase F planner and interval domain", () => {
  it("generates month, custom, and selected-date proposals with weekday defaults", () => { expect(monthRange(2028, 2)).toEqual({ startDate: "2028-02-01", endDate: "2028-02-29" }); const proposal = generateCalendarProposal({ mode: "CUSTOM_RANGE", startDate: "2026-01-03", endDate: "2026-01-05", policy }); expect(proposal.map((day) => day.date)).toEqual(["2026-01-03", "2026-01-04", "2026-01-05"]); expect(proposal.find((day) => day.date === "2026-01-04")?.enabled).toBe(false); expect(generateCalendarProposal({ mode: "SELECTED_DATES", startDate: "", endDate: "", selectedDates: ["2026-01-05", "2026-01-05"], policy })).toHaveLength(1); });
  it("provides pure interval operations", () => { const first = makeInterval("2026-01-05", timeToMinutes("08:00"), timeToMinutes("11:00"))!; const second = makeInterval("2026-01-05", timeToMinutes("11:30"), timeToMinutes("14:30"))!; expect(intervalDuration(first)).toBe(180); expect(intervalsOverlap(first, second)).toBe(false); expect(intervalsAdjacent(first, second, 30)).toBe(true); expect(intervalContains(first, first)).toBe(true); expect(minutesToTime(690)).toBe("11:30"); });
  it("fits three three-hour exams in one hall with turnaround", () => { const result = generateFlexibleAggregateTimetable(dataset([event("A"), event("B"), event("C")]), { maxGenerationAttempts: 1 }); expect(result.unscheduledEvents).toHaveLength(0); expect(result.assignments.map((item) => `${item.startTime}-${item.endTime}`)).toEqual(["08:00-11:00", "11:30-14:30", "15:00-18:00"]); expect(validateAggregateTimetable(result, dataset([event("A"), event("B"), event("C")]))).toEqual([]); });
  it("uses a day-specific turnaround override when scheduling flexible intervals", () => { const input = dataset([event("A"), event("B")]); input.calendarDays = [{ ...input.calendarDays![0], turnaroundMinutesOverride: 60 }]; const result = generateFlexibleAggregateTimetable(input, { maxGenerationAttempts: 1 }); expect(result.unscheduledEvents).toHaveLength(0); expect(result.assignments.map((item) => `${item.startTime}-${item.endTime}`).sort()).toEqual(["08:00-11:00", "12:00-15:00"]); });
  it("reports blocked, tight, and likely-feasible planner states", () => { const days: PlannerDay[] = [{ date: "2026-01-05", enabled: true, dayType: "WEEKDAY", startTime: "08:00", endTime: "18:00" }]; const blocked = assessPlannerFeasibility(days, [event("LONG", 700)], [], undefined); expect(blocked.status).toBe("BLOCKED"); const tight = assessPlannerFeasibility(days, [event("A", 480)], dataset([event("A")]).venues, undefined); expect(["TIGHT", "LIKELY_FEASIBLE"]).toContain(tight.status); const likely = assessPlannerFeasibility([...days, { ...days[0], date: "2026-01-06" }], [event("A", 60)], dataset([event("A")]).venues, undefined); expect(likely.status).toBe("LIKELY_FEASIBLE"); });
});
