import type { TimetableEngineConfig } from "../config";
import type { CandidateTimetable, SchedulingDataset, TimetableMetrics } from "../types";

function slotOrder(dataset: SchedulingDataset) { return new Map(dataset.timeSlots.slice().sort((a, b) => `${a.date}|${a.startTime}|${a.id}`.localeCompare(`${b.date}|${b.startTime}|${b.id}`)).map((slot, index) => [slot.id, index])); }

export function calculateMetrics(timetable: CandidateTimetable, dataset: SchedulingDataset, config: TimetableEngineConfig): TimetableMetrics {
  const slots = new Map(dataset.timeSlots.map((slot) => [slot.id, slot])); const slotIndexes = slotOrder(dataset); const students = new Map<string, { slotId: string; date: string }[]>(); const courses = new Map(dataset.courses.map((course) => [course.id, course])); const registrationsByCourse = new Map<string, string[]>();
  for (const registration of dataset.registrations) registrationsByCourse.set(registration.courseId, [...(registrationsByCourse.get(registration.courseId) ?? []), registration.studentId]);
  let totalUnusedSeats = 0; let venueSplitCount = 0;
  for (const assignment of timetable.assignments) { totalUnusedSeats += assignment.venues.reduce((sum, venue) => sum + venue.allocatedCapacity, 0) - (registrationsByCourse.get(assignment.courseId)?.length ?? courses.get(assignment.courseId)?.estimatedStudentCount ?? 0); if (assignment.venues.length > 1) venueSplitCount += 1; for (const studentId of registrationsByCourse.get(assignment.courseId) ?? []) { const slot = slots.get(assignment.timeSlotId); if (slot) students.set(studentId, [...(students.get(studentId) ?? []), { slotId: slot.id, date: slot.date }]); } }
  let studentBackToBackCount = 0; let studentDailyOverloadCount = 0;
  for (const exams of students.values()) { const sorted = exams.slice().sort((a, b) => (slotIndexes.get(a.slotId) ?? 0) - (slotIndexes.get(b.slotId) ?? 0)); for (let index = 1; index < sorted.length; index += 1) if (sorted[index].date === sorted[index - 1].date && (slotIndexes.get(sorted[index].slotId) ?? 0) - (slotIndexes.get(sorted[index - 1].slotId) ?? 0) === 1) studentBackToBackCount += 1; const daily = new Map<string, number>(); for (const exam of exams) daily.set(exam.date, (daily.get(exam.date) ?? 0) + 1); for (const count of daily.values()) if (count > config.maxStudentExamsPerDay) studentDailyOverloadCount += count - config.maxStudentExamsPerDay; }
  const invigilatorLoads = new Map<string, number>(); const invigilatorDailyLoads = new Map<string, number>(); for (const assignment of timetable.assignments) { const slot = slots.get(assignment.timeSlotId); for (const invigilator of assignment.invigilators) { invigilatorLoads.set(invigilator.invigilatorId, (invigilatorLoads.get(invigilator.invigilatorId) ?? 0) + 1); if (slot) invigilatorDailyLoads.set(`${invigilator.invigilatorId}|${slot.date}`, (invigilatorDailyLoads.get(`${invigilator.invigilatorId}|${slot.date}`) ?? 0) + 1); } }
  const loads = dataset.invigilators.map((invigilator) => invigilatorLoads.get(invigilator.id) ?? 0); const average = loads.length ? loads.reduce((sum, load) => sum + load, 0) / loads.length : 0; const variance = loads.length ? loads.reduce((sum, load) => sum + (load - average) ** 2, 0) / loads.length : 0;
  const invigilatorDailyOverloadCount = [...invigilatorDailyLoads.entries()].reduce((total, [key, count]) => { const invigilator = dataset.invigilators.find((candidate) => candidate.id === key.split("|")[0]); return total + (invigilator ? Math.max(0, count - invigilator.maximumDailyAssignments) : 0); }, 0); const totalAllocatedCapacity = timetable.assignments.reduce((sum, assignment) => sum + assignment.venues.reduce((inner, venue) => inner + venue.allocatedCapacity, 0), 0);
  return { totalCourses: dataset.courses.length, scheduledCourses: timetable.assignments.length, unscheduledCourses: timetable.unscheduledCourses.length, totalCandidates: dataset.students.length, hardViolationCount: timetable.hardViolations.length, averageVenueUtilization: totalAllocatedCapacity ? 1 - totalUnusedSeats / totalAllocatedCapacity : 0, totalUnusedSeats, studentBackToBackCount, studentDailyOverloadCount, invigilatorDailyOverloadCount, invigilatorAssignmentMin: loads.length ? Math.min(...loads) : 0, invigilatorAssignmentMax: loads.length ? Math.max(...loads) : 0, invigilatorAssignmentAverage: average, invigilatorWorkloadVariance: variance, venueSplitCount };
}

export function scoreTimetable(timetable: CandidateTimetable, dataset: SchedulingDataset, config: TimetableEngineConfig) {
  const metrics = calculateMetrics(timetable, dataset, config); const venueWaste = metrics.totalUnusedSeats * config.venueWastePenaltyWeight; const venueSplitting = metrics.venueSplitCount * config.venueSplitPenalty; const backToBack = metrics.studentBackToBackCount * config.studentBackToBackPenalty; const overload = metrics.studentDailyOverloadCount * config.studentDailyOverloadPenalty; const balance = metrics.invigilatorWorkloadVariance * config.invigilatorBalancePenaltyWeight; const dailyOverload = metrics.invigilatorDailyOverloadCount * config.dailyInvigilatorOverloadPenalty; const unscheduled = metrics.unscheduledCourses * 10000; const hard = metrics.hardViolationCount * 100000; const distribution = distributionPenalty(timetable, dataset);
  return { penalty: hard + unscheduled + backToBack + overload + venueWaste + venueSplitting + balance + dailyOverload + distribution, details: { hard, unscheduled, backToBack, overload, venueWaste, venueSplitting, balance, dailyOverload, distribution }, metrics };
}

function distributionPenalty(timetable: CandidateTimetable, dataset: SchedulingDataset) { if (!timetable.assignments.length || !dataset.timeSlots.length) return 0; const indexes = new Map(dataset.timeSlots.map((slot, index) => [slot.id, index])); const average = timetable.assignments.reduce((sum, assignment) => sum + (indexes.get(assignment.timeSlotId) ?? 0), 0) / timetable.assignments.length; return average < (dataset.timeSlots.length - 1) / 2 ? ((dataset.timeSlots.length - 1) / 2 - average) * 2 : 0; }
