"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { AlertCircle, ArrowLeft, Check, RefreshCw, ShieldAlert } from "lucide-react";

import { Button } from "@/components/ui/button";

type Row = Record<string, any>;
const writableRoles = ["SUPER_ADMIN", "ADMIN", "EXAM_OFFICER"];
const text = (value: unknown) => value == null ? "" : String(value);

export function AggregateConflictsWorkspace({ role }: { role: string }) {
  const writable = writableRoles.includes(role);
  const [sessions, setSessions] = useState<Row[]>([]);
  const [semesters, setSemesters] = useState<Row[]>([]);
  const [courses, setCourses] = useState<Row[]>([]);
  const [sessionId, setSessionId] = useState("");
  const [semesterId, setSemesterId] = useState("");
  const [conflicts, setConflicts] = useState<Row[]>([]);
  const [dataset, setDataset] = useState<Row | null>(null);
  const [readiness, setReadiness] = useState<Row | null>(null);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  const [editingId, setEditingId] = useState("");
  const [form, setForm] = useState({ courseAId: "", courseBId: "", severity: "HARD", type: "MANUAL", estimatedSharedCandidates: "", reason: "" });

  const filteredSemesters = useMemo(() => semesters.filter((item) => !sessionId || item.academicSessionId === sessionId), [semesters, sessionId]);
  const eventById = useMemo<Map<string, Row>>(() => new Map((dataset?.events ?? []).map((event: Row) => [event.id, event] as [string, Row])), [dataset]);

  async function loadDependencies() {
    const responses = await Promise.all([fetch("/api/academic/sessions?active=true", { cache: "no-store" }), fetch("/api/academic/semesters?active=true", { cache: "no-store" })]);
    const bodies = await Promise.all(responses.map((response) => response.json()));
    setSessions(bodies[0].data ?? []); setSemesters(bodies[1].data ?? []);
    if (!sessionId && bodies[0].data?.[0]) setSessionId(bodies[0].data[0].id);
  }

  async function loadData() {
    if (!sessionId || !semesterId) return;
    const query = `academicSessionId=${encodeURIComponent(sessionId)}&semesterId=${encodeURIComponent(semesterId)}`;
    const responses = await Promise.all([fetch(`/api/resources/courses?semesterId=${encodeURIComponent(semesterId)}&active=true&pageSize=200`, { cache: "no-store" }), fetch(`/api/exams/conflicts?${query}&active=all`, { cache: "no-store" }), fetch(`/api/exams/conflicts/graph?${query}`, { cache: "no-store" }), fetch(`/api/exams/course-loads/readiness?${query}`, { cache: "no-store" })]);
    const bodies = await Promise.all(responses.map((response) => response.json()));
    setCourses(bodies[0].data?.rows ?? []); setConflicts(bodies[1].data ?? []); setDataset(bodies[2].data ?? null); setReadiness(bodies[3].data ?? null);
  }

  useEffect(() => { void loadDependencies(); }, []);
  useEffect(() => { if (sessionId && !semesterId) { const first = semesters.find((item) => item.academicSessionId === sessionId); if (first) setSemesterId(first.id); } }, [sessionId, semesters, semesterId]);
  useEffect(() => { void loadData(); }, [sessionId, semesterId]);

  async function saveConflict(event: React.FormEvent) {
    event.preventDefault(); setBusy(true); setError(""); setMessage("");
    try {
      const endpoint = editingId ? `/api/exams/conflicts/${editingId}` : "/api/exams/conflicts";
      const body = editingId ? { severity: form.severity, type: form.type, estimatedSharedCandidates: form.estimatedSharedCandidates ? Number(form.estimatedSharedCandidates) : null, reason: form.reason } : { ...form, academicSessionId: sessionId, semesterId, estimatedSharedCandidates: form.estimatedSharedCandidates ? Number(form.estimatedSharedCandidates) : null };
      const response = await fetch(endpoint, { method: editingId ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
      const result = await response.json(); if (!response.ok) throw new Error(result.error?.message ?? "Unable to save explicit conflict.");
      setMessage(editingId ? "Explicit conflict updated." : "Explicit conflict added."); setEditingId(""); setForm({ courseAId: "", courseBId: "", severity: "HARD", type: "MANUAL", estimatedSharedCandidates: "", reason: "" }); await loadData();
    } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to save explicit conflict."); } finally { setBusy(false); }
  }

  async function setActive(id: string, active: boolean) {
    setBusy(true); setError(""); setMessage("");
    try { const response = await fetch(`/api/exams/conflicts/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ active }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error?.message ?? "Unable to update conflict status."); setMessage(active ? "Explicit conflict reactivated." : "Explicit conflict deactivated."); await loadData(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to update conflict status."); } finally { setBusy(false); }
  }

  function editConflict(conflict: Row) { setEditingId(conflict.id); setForm({ courseAId: conflict.courseAId, courseBId: conflict.courseBId, severity: conflict.severity, type: conflict.type, estimatedSharedCandidates: conflict.estimatedSharedCandidates == null ? "" : String(conflict.estimatedSharedCandidates), reason: conflict.reason ?? "" }); }
  const courseLabel = (id: string) => { const course = courses.find((item) => item.id === id); return course ? `${course.code} — ${course.title}` : id; };

  return <div className="space-y-6"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><Link href="/exam-planning/course-loads" className="mb-4 inline-flex items-center gap-1.5 text-sm font-semibold text-slate-400 hover:text-teal"><ArrowLeft className="h-4 w-4" />Course loads</Link><p className="mb-2 text-sm font-semibold text-teal">EXAM PLANNING</p><h1 className="text-3xl font-bold tracking-tight text-navy">Conflicts and readiness</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">Inspect automatic programme/level clashes and record known exceptions. Student names are never required.</p></div><Button variant="outline" size="icon" onClick={() => void loadData()} aria-label="Refresh"><RefreshCw className="h-4 w-4" /></Button></div>
    <div className="grid gap-3 rounded-xl border border-slate-200 bg-white p-4 shadow-card md:grid-cols-2"><label className="text-sm font-semibold text-slate-700">Academic session<select value={sessionId} onChange={(event) => setSessionId(event.target.value)} className="mt-2 h-10 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm"><option value="">Select session</option>{sessions.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="text-sm font-semibold text-slate-700">Semester<select value={semesterId} onChange={(event) => setSemesterId(event.target.value)} className="mt-2 h-10 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm"><option value="">Select semester</option>{filteredSemesters.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label></div>
    {(error || message) && <div role="status" className={`flex gap-2 rounded-lg border p-3 text-sm ${error ? "border-red-200 bg-red-50 text-red-700" : "border-emerald-200 bg-emerald-50 text-emerald-700"}`}>{error ? <AlertCircle className="h-4 w-4" /> : <Check className="h-4 w-4" />}{error || message}</div>}
    {readiness && <ReadinessSummary readiness={readiness} />}
    <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-card"><div className="flex items-center justify-between"><div><h2 className="font-bold text-navy">Explicit conflicts</h2><p className="mt-1 text-sm text-slate-500">Use this list for carryovers, electives, department rules, and other known restrictions. Cohort conflicts are detected automatically below.</p></div><ShieldAlert className="h-5 w-5 text-teal" /></div>{writable && <form onSubmit={saveConflict} className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3"><Select label="Course A" value={form.courseAId} options={courses.map((course) => ({ value: course.id, label: `${course.code} — ${course.title}` }))} onChange={(value) => setForm({ ...form, courseAId: value })} /><Select label="Course B" value={form.courseBId} options={courses.map((course) => ({ value: course.id, label: `${course.code} — ${course.title}` }))} onChange={(value) => setForm({ ...form, courseBId: value })} /><Select label="Severity" value={form.severity} options={[{ value: "HARD", label: "Hard — never overlap" }, { value: "SOFT", label: "Soft — prefer separate" }]} onChange={(value) => setForm({ ...form, severity: value })} /><Select label="Type" value={form.type} options={[{ value: "CARRYOVER", label: "Carryover" }, { value: "ELECTIVE_OVERLAP", label: "Elective overlap" }, { value: "DEPARTMENT_RULE", label: "Department rule" }, { value: "MANUAL", label: "Manual restriction" }]} onChange={(value) => setForm({ ...form, type: value })} /><Field label="Estimated overlap" value={form.estimatedSharedCandidates} type="number" optional onChange={(value) => setForm({ ...form, estimatedSharedCandidates: value })} /><Field label="Reason" value={form.reason} optional onChange={(value) => setForm({ ...form, reason: value })} /><div className="flex items-end gap-2"><Button disabled={busy || !sessionId || !semesterId || !form.courseAId || !form.courseBId}>{editingId ? "Update conflict" : "Add conflict"}</Button>{editingId && <Button type="button" variant="outline" onClick={() => { setEditingId(""); setForm({ courseAId: "", courseBId: "", severity: "HARD", type: "MANUAL", estimatedSharedCandidates: "", reason: "" }); }}>Cancel</Button>}</div></form>}
      <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wider text-slate-400"><tr><th className="px-4 py-3">Courses</th><th className="px-4 py-3">Severity</th><th className="px-4 py-3">Type</th><th className="px-4 py-3">Overlap</th><th className="px-4 py-3">Status</th>{writable && <th className="px-4 py-3">Actions</th>}</tr></thead><tbody className="divide-y divide-slate-100">{conflicts.map((conflict) => <tr key={conflict.id}><td className="px-4 py-4 font-semibold text-navy">{conflict.courseA?.code} ↔ {conflict.courseB?.code}<p className="mt-1 text-xs font-normal text-slate-400">{conflict.reason || "No additional reason"}</p></td><td className="px-4 py-4"><span className={conflict.severity === "HARD" ? "font-semibold text-red-700" : "font-semibold text-amber-700"}>{conflict.severity}</span></td><td className="px-4 py-4 text-slate-500">{conflict.type}</td><td className="px-4 py-4 text-slate-500">{conflict.estimatedSharedCandidates ?? "—"}</td><td className="px-4 py-4 text-slate-500">{conflict.active ? "Active" : "Inactive"}</td>{writable && <td className="px-4 py-4"><div className="flex gap-2"><button className="text-xs font-semibold text-teal" onClick={() => editConflict(conflict)}>Edit</button><button className="text-xs font-semibold text-slate-500" onClick={() => void setActive(conflict.id, !conflict.active)}>{conflict.active ? "Deactivate" : "Reactivate"}</button></div></td>}</tr>)}</tbody></table>{!conflicts.length && <p className="p-8 text-center text-sm text-slate-400">No explicit conflicts recorded for this semester.</p>}</div></section>
    <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-card"><div><h2 className="font-bold text-navy">Automatic conflict inspector</h2><p className="mt-1 text-sm text-slate-500">These edges come from shared programme/level cohorts, explicit conflicts, and optional registration precision. They are not generated timetable collisions.</p></div><div className="mt-5 space-y-3">{(dataset?.graph?.edges ?? []).map((edge: Row) => { const left = eventById.get(edge.eventAId); const right = eventById.get(edge.eventBId); return <article key={`${edge.eventAId}-${edge.eventBId}`} className="rounded-lg border border-slate-200 p-4"><div className="flex flex-col justify-between gap-2 md:flex-row"><p className="font-semibold text-navy">{left?.title ?? edge.eventAId} ↔ {right?.title ?? edge.eventBId}</p><span className={edge.hard ? "text-xs font-bold text-red-700" : "text-xs font-bold text-amber-700"}>{edge.hard ? "HARD" : "SOFT/REVIEW"} · weight {edge.weight}</span></div><div className="mt-3 flex flex-wrap gap-2">{edge.reasons.map((reason: Row, index: number) => <span key={`${reason.type}-${index}`} className="rounded-full bg-slate-100 px-2.5 py-1 text-xs text-slate-600">{reason.label}{reason.programmeName ? ` · ${reason.programmeName} ${reason.level}L · ${reason.candidateCount}` : reason.studentCount ? ` · ${reason.studentCount} registrations` : ""}</span>)}</div></article>; })}{!(dataset?.graph?.edges ?? []).length && <p className="rounded-lg border border-dashed border-slate-200 p-8 text-center text-sm text-slate-400">No automatic or explicit aggregate conflict edges for this selection.</p>}</div></section>
  </div>;
}

function ReadinessSummary({ readiness }: { readiness: Row }) { return <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-card"><div className="flex flex-col justify-between gap-3 md:flex-row md:items-center"><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Aggregate readiness</p><h2 className={`mt-1 text-2xl font-bold ${readiness.status === "BLOCKED" ? "text-red-700" : readiness.status === "READY" ? "text-emerald-700" : "text-amber-700"}`}>{readiness.status}</h2></div><div className="grid grid-cols-2 gap-3 text-right sm:grid-cols-4"><Metric label="Events" value={readiness.metrics?.events ?? readiness.logicalExamCount} /><Metric label="Edges" value={readiness.metrics?.edges ?? 0} /><Metric label="Density" value={`${Math.round((readiness.metrics?.density ?? 0) * 100)}%`} /><Metric label="Workload" value={readiness.metrics?.candidateVolume ?? 0} /></div></div><div className="mt-4 grid gap-2 text-sm sm:grid-cols-2 lg:grid-cols-4"><Checklist label="Academic session" ok={readiness.sessionExists} /><Checklist label="Course loads" ok={readiness.courseOfferingsLoaded} /><Checklist label="Candidate counts" ok={readiness.candidateCountsComplete} /><Checklist label="Exam events" ok={readiness.logicalExamCount > 0} /><Checklist label="Modes" ok={!readiness.blockers?.some((item: Row) => item.code === "UNRESOLVED_EXAM_MODE")} /><Checklist label="Durations" ok={!readiness.blockers?.some((item: Row) => item.code === "UNRESOLVED_DURATION")} /><Checklist label="Conflict graph" ok={!readiness.blockers?.some((item: Row) => item.code === "INVALID_EXPLICIT_CONFLICT")} /><Checklist label="Student precision" ok={true} note="Optional" /></div>{readiness.highConflictEvents?.length > 0 && <div className="mt-4 rounded-lg border border-slate-100 p-3"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Most constrained events</p>{readiness.highConflictEvents.slice(0, 5).map((item: Row) => <p key={item.eventId} className="mt-1 text-sm text-slate-600">{item.eventId} · {item.conflictDegree} conflicts · weighted {item.weightedConflictDegree}</p>)}</div>}{(readiness.blockers?.length || readiness.warnings?.length) ? <div className="mt-4 space-y-1">{[...(readiness.blockers ?? []), ...(readiness.warnings ?? [])].slice(0, 8).map((item: Row) => <p key={item.code} className={item.severity === "BLOCKER" ? "text-sm text-red-700" : "text-sm text-amber-700"}>{item.code}: {item.message}</p>)}</div> : <p className="mt-4 text-sm text-emerald-700">All aggregate checks are clear.</p>}</section>; }
function Metric({ label, value }: { label: string; value: unknown }) { return <div><p className="text-[11px] font-semibold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 font-bold text-navy">{text(value)}</p></div>; }
function Checklist({ label, ok, note }: { label: string; ok: boolean; note?: string }) { return <div className="flex items-center gap-2 rounded-lg border border-slate-100 px-3 py-2"><span className={ok ? "text-emerald-600" : "text-red-600"}>{ok ? "✓" : "!"}</span><span className="text-slate-600">{label}</span>{note && <span className="text-xs text-slate-400">({note})</span>}</div>; }
function Field({ label, value, type = "text", optional = false, onChange }: { label: string; value: string; type?: string; optional?: boolean; onChange: (value: string) => void }) { return <label className="text-sm font-semibold text-slate-700">{label}<input required={!optional} type={type} value={value} onChange={(event) => onChange(event.target.value)} className="mt-2 h-10 w-full rounded-lg border border-slate-200 px-3 text-sm font-normal" /></label>; }
function Select({ label, value, options, onChange }: { label: string; value: string; options: { value: string; label: string }[]; onChange: (value: string) => void }) { return <label className="text-sm font-semibold text-slate-700">{label}<select required value={value} onChange={(event) => onChange(event.target.value)} className="mt-2 h-10 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm font-normal"><option value="">Select</option>{options.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label>; }
