"use client";

import { useEffect, useState } from "react";
import { CalendarDays, Loader2, Save, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { monthRange } from "@/domain/timetable/planner";

type Row = Record<string, any>;
type Mode = "WHOLE_MONTH" | "CUSTOM_RANGE" | "SELECTED_DATES";
type Day = { date: string; enabled: boolean; dayType: string; startTime: string; endTime: string; turnaroundMinutesOverride?: number | null; blackoutType?: string | null; reason?: string | null };
type CbtPolicy = { enabled: boolean; minimumBatchGapMinutes: number; maxBatchesPerDay: number | null; requireSameDay: boolean; allowMultiDay: boolean; preferMaximumCapacityPerBatch: boolean; minimumInvigilatorsPerVenue: number; minimumTechnicalSupportPerVenue: number; additionalSupportPerCandidates: number | null };

const defaultCbtPolicy: CbtPolicy = { enabled: false, minimumBatchGapMinutes: 30, maxBatchesPerDay: null, requireSameDay: true, allowMultiDay: false, preferMaximumCapacityPerBatch: true, minimumInvigilatorsPerVenue: 1, minimumTechnicalSupportPerVenue: 1, additionalSupportPerCandidates: null };
const blackoutOptions = [{ value: "", label: "No blackout" }, { value: "PUBLIC_HOLIDAY", label: "Public holiday" }, { value: "UNIVERSITY_EVENT", label: "University event" }, { value: "NO_EXAMS", label: "No exams" }, { value: "OTHER", label: "Other" }];

function cbtPolicyFromPeriod(period: Row): CbtPolicy {
  return { enabled: Boolean(period.cbtBatchingEnabled), minimumBatchGapMinutes: Number(period.cbtMinimumBatchGapMinutes ?? 30), maxBatchesPerDay: period.cbtMaxBatchesPerDay == null ? null : Number(period.cbtMaxBatchesPerDay), requireSameDay: period.cbtRequireSameDay !== false, allowMultiDay: Boolean(period.cbtAllowMultiDay), preferMaximumCapacityPerBatch: period.cbtPreferMaximumCapacityPerBatch !== false, minimumInvigilatorsPerVenue: Number(period.cbtMinimumInvigilatorsPerVenue ?? 1), minimumTechnicalSupportPerVenue: Number(period.cbtMinimumTechnicalSupportPerVenue ?? 1), additionalSupportPerCandidates: period.cbtAdditionalSupportPerCandidates == null ? null : Number(period.cbtAdditionalSupportPerCandidates) };
}

function isRealDate(value: string) { const parsed = new Date(`${value}T00:00:00.000Z`); return /^\d{4}-\d{2}-\d{2}$/.test(value) && !Number.isNaN(parsed.getTime()) && parsed.toISOString().slice(0, 10) === value; }

export function ExamPeriodPlanner({ role }: { role: string }) {
  const writable = ["SUPER_ADMIN", "ADMIN", "EXAM_OFFICER"].includes(role);
  const [periods, setPeriods] = useState<Row[]>([]);
  const [periodId, setPeriodId] = useState("");
  const [period, setPeriod] = useState<Row | null>(null);
  const [days, setDays] = useState<Day[]>([]);
  const [mode, setMode] = useState<Mode>("WHOLE_MONTH");
  const [month, setMonth] = useState("");
  const [startDate, setStartDate] = useState("");
  const [endDate, setEndDate] = useState("");
  const [selectedDates, setSelectedDates] = useState<string[]>([]);
  const [selectedDateInput, setSelectedDateInput] = useState("");
  const [weekends, setWeekends] = useState(false);
  const [cbtPolicy, setCbtPolicy] = useState<CbtPolicy>(defaultCbtPolicy);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  const [capacity, setCapacity] = useState<Row | null>(null);

  useEffect(() => { void fetch("/api/academic/exam-periods?active=true").then((response) => response.json()).then((body) => setPeriods(body.data ?? [])); }, []);
  useEffect(() => {
    if (!periodId) { setPeriod(null); setDays([]); setSelectedDates([]); return; }
    void fetch(`/api/exam-planning/period?examPeriodId=${periodId}`, { cache: "no-store" }).then((response) => response.json()).then((body) => {
      if (!body.data) return;
      const loadedPeriod = body.data.period as Row;
      const loadedDays = (body.data.days ?? []) as Day[];
      setPeriod(loadedPeriod); setDays(loadedDays); setStartDate(loadedPeriod.startDate); setEndDate(loadedPeriod.endDate); setMonth(loadedPeriod.startDate.slice(0, 7)); setSelectedDates(loadedDays.filter((day) => day.enabled).map((day) => day.date)); setCbtPolicy(cbtPolicyFromPeriod(loadedPeriod)); setCapacity(null); setError("");
    });
  }, [periodId]);

  function policy() { return { defaultDayStartTime: period?.defaultDayStartTime ?? "08:00", defaultDayEndTime: period?.defaultDayEndTime ?? "18:00", defaultTurnaroundMinutes: Number(period?.defaultTurnaroundMinutes ?? 30), writtenTurnaroundMinutes: Number(period?.writtenTurnaroundMinutes ?? 30), cbtTurnaroundMinutes: Number(period?.cbtTurnaroundMinutes ?? 15), timeGranularityMinutes: Number(period?.timeGranularityMinutes ?? 30), weekdays: [weekends, true, true, true, true, true, weekends], cbtBatchingEnabled: cbtPolicy.enabled, cbtMinimumBatchGapMinutes: cbtPolicy.minimumBatchGapMinutes, cbtMaxBatchesPerDay: cbtPolicy.maxBatchesPerDay, cbtRequireSameDay: cbtPolicy.requireSameDay, cbtAllowMultiDay: cbtPolicy.allowMultiDay, cbtPreferMaximumCapacityPerBatch: cbtPolicy.preferMaximumCapacityPerBatch, cbtMinimumInvigilatorsPerVenue: cbtPolicy.minimumInvigilatorsPerVenue, cbtMinimumTechnicalSupportPerVenue: cbtPolicy.minimumTechnicalSupportPerVenue, cbtAdditionalSupportPerCandidates: cbtPolicy.additionalSupportPerCandidates }; }
  function updateCbt(patch: Partial<CbtPolicy>) { setCbtPolicy((current) => ({ ...current, ...patch })); }
  function changeMonth(value: string) { setMonth(value); if (!/^\d{4}-\d{2}$/.test(value)) return; const [year, monthNumber] = value.split("-").map(Number); const range = monthRange(year, monthNumber); setStartDate(range.startDate); setEndDate(range.endDate); }
  function addSelectedDate() { setError(""); if (!period || !isRealDate(selectedDateInput)) { setError("Choose a valid calendar date."); return; } if (selectedDateInput < period.startDate || selectedDateInput > period.endDate) { setError("Selected dates must fall inside the examination period."); return; } if (selectedDates.includes(selectedDateInput)) { setError("That date is already selected."); return; } setSelectedDates([...selectedDates, selectedDateInput].sort()); setSelectedDateInput(""); }
  function removeSelectedDate(date: string) { setSelectedDates((current) => current.filter((item) => item !== date)); }
  async function preview() {
    if (!periodId) return;
    setBusy(true); setError(""); setMessage("");
    const range = mode === "WHOLE_MONTH" && /^\d{4}-\d{2}$/.test(month) ? monthRange(Number(month.slice(0, 4)), Number(month.slice(5, 7))) : { startDate, endDate };
    if (mode === "SELECTED_DATES" && !selectedDates.length) { setError("Select at least one date before previewing."); setBusy(false); return; }
    try { const response = await fetch("/api/exam-planning/period", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ examPeriodId: periodId, mode, ...range, selectedDates: mode === "SELECTED_DATES" ? selectedDates : undefined, policy: policy() }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message ?? "Planner preview failed."); setStartDate(range.startDate); setEndDate(range.endDate); setDays(body.data.days ?? []); setMessage("Calendar proposal ready. Review the days below before saving."); } catch (caught) { setError(caught instanceof Error ? caught.message : "Planner preview failed."); } finally { setBusy(false); }
  }
  async function save() {
    if (!periodId) return;
    setBusy(true); setError("");
    try { const response = await fetch("/api/exam-planning/period", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ examPeriodId: periodId, mode, startDate, endDate, selectedDates: mode === "SELECTED_DATES" ? selectedDates : undefined, policy: policy(), days }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message ?? "Calendar could not be saved."); setPeriod(body.data.period); setDays(body.data.days ?? days); setCbtPolicy(cbtPolicyFromPeriod(body.data.period)); setMessage("Exam calendar and CBT policy saved."); } catch (caught) { setError(caught instanceof Error ? caught.message : "Calendar could not be saved."); } finally { setBusy(false); }
  }
  async function loadCapacity() { if (!periodId) return; setBusy(true); setError(""); try { const response = await fetch(`/api/exam-planning/period/capacity?examPeriodId=${periodId}`, { cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message ?? "Capacity check failed."); setCapacity(body.data); } catch (caught) { setError(caught instanceof Error ? caught.message : "Capacity check failed."); } finally { setBusy(false); } }
  function updateDay(index: number, patch: Partial<Day>) { setDays((current) => current.map((day, item) => item === index ? { ...day, ...patch } : day)); }

  return <div className="space-y-6">
    <section className="rounded-xl border border-slate-200 bg-white p-6 shadow-card">
      <div className="flex items-start gap-3"><CalendarDays className="mt-1 h-6 w-6 text-teal" /><div><p className="text-xs font-bold uppercase tracking-wider text-teal">Exam planning</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-navy">Exam-period calendar</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Choose eligible exam days, daily hours, turnaround, and CBT batching policy.</p></div></div>
      <div className="mt-6 grid gap-4 md:grid-cols-3"><label className="text-sm font-semibold text-slate-700">Examination period<select value={periodId} onChange={(event) => setPeriodId(event.target.value)} className="mt-2 h-11 w-full rounded-lg border border-slate-200 px-3 font-normal"><option value="">Select...</option>{periods.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="text-sm font-semibold text-slate-700">Planner mode<select value={mode} onChange={(event) => setMode(event.target.value as Mode)} className="mt-2 h-11 w-full rounded-lg border border-slate-200 px-3 font-normal"><option value="WHOLE_MONTH">Whole month</option><option value="CUSTOM_RANGE">Custom range</option><option value="SELECTED_DATES">Selected dates</option></select></label><label className="flex items-end gap-2 pb-2 text-sm text-slate-600"><input type="checkbox" checked={weekends} disabled={!writable} onChange={(event) => setWeekends(event.target.checked)} /> Allow weekend exams</label></div>
      {mode === "WHOLE_MONTH" && <label className="mt-4 block max-w-xs text-sm font-semibold text-slate-700">Month<input type="month" value={month} disabled={!writable} onChange={(event) => changeMonth(event.target.value)} className="mt-2 h-11 w-full rounded-lg border border-slate-200 px-3 font-normal" /></label>}
      {mode === "CUSTOM_RANGE" && <div className="mt-4 grid gap-4 md:grid-cols-2"><label className="text-sm font-semibold text-slate-700">Start date<input type="date" value={startDate} disabled={!writable} onChange={(event) => setStartDate(event.target.value)} className="mt-2 h-11 w-full rounded-lg border border-slate-200 px-3 font-normal" /></label><label className="text-sm font-semibold text-slate-700">End date<input type="date" value={endDate} disabled={!writable} onChange={(event) => setEndDate(event.target.value)} className="mt-2 h-11 w-full rounded-lg border border-slate-200 px-3 font-normal" /></label></div>}
      {mode === "SELECTED_DATES" && <div className="mt-4 rounded-lg border border-slate-200 p-4"><p className="text-sm font-semibold text-slate-700">Select individual dates</p><div className="mt-3 flex flex-wrap gap-2"><input type="date" value={selectedDateInput} disabled={!writable} min={period?.startDate} max={period?.endDate} onChange={(event) => setSelectedDateInput(event.target.value)} className="h-10 rounded-lg border border-slate-200 px-3 text-sm" /><Button type="button" variant="outline" disabled={!writable || !selectedDateInput} onClick={addSelectedDate}>Add date</Button></div><div className="mt-3 flex flex-wrap gap-2">{selectedDates.map((date) => <span key={date} className="inline-flex items-center gap-1 rounded-full bg-teal/10 px-3 py-1 text-sm text-teal">{date}{writable && <button type="button" aria-label={`Remove ${date}`} onClick={() => removeSelectedDate(date)}><X className="h-3.5 w-3.5" /></button>}</span>)}{!selectedDates.length && <span className="text-sm text-slate-400">No dates selected yet.</span>}</div></div>}
      {period && <div className="mt-5 grid gap-3 rounded-lg bg-slate-50 p-4 text-sm sm:grid-cols-4"><Stat label="Period" value={period.name} /><Stat label="Default hours" value={`${period.defaultDayStartTime}–${period.defaultDayEndTime}`} /><Stat label="Turnaround" value={`${period.defaultTurnaroundMinutes} min`} /><Stat label="Granularity" value={`${period.timeGranularityMinutes} min`} /></div>}
      {period && <section className="mt-5 rounded-lg border border-slate-200 p-4"><h2 className="font-bold text-navy">CBT batching policy</h2><div className="mt-4 grid gap-4 md:grid-cols-2 lg:grid-cols-4"><label className="flex items-center gap-2 text-sm text-slate-600"><input type="checkbox" checked={cbtPolicy.enabled} disabled={!writable} onChange={(event) => updateCbt({ enabled: event.target.checked })} /> Enable batching</label><NumberField label="Minimum batch gap (minutes)" value={cbtPolicy.minimumBatchGapMinutes} disabled={!writable} onChange={(value) => updateCbt({ minimumBatchGapMinutes: value })} /><label className="text-sm font-semibold text-slate-700">Max batches per day<input type="number" min="1" max="20" value={cbtPolicy.maxBatchesPerDay ?? ""} disabled={!writable} placeholder="No limit" onChange={(event) => updateCbt({ maxBatchesPerDay: event.target.value ? Number(event.target.value) : null })} className="mt-2 h-10 w-full rounded-lg border border-slate-200 px-3 font-normal" /></label><NumberField label="Invigilators per venue" value={cbtPolicy.minimumInvigilatorsPerVenue} disabled={!writable} onChange={(value) => updateCbt({ minimumInvigilatorsPerVenue: value })} /><NumberField label="Technical support per venue" value={cbtPolicy.minimumTechnicalSupportPerVenue} disabled={!writable} onChange={(value) => updateCbt({ minimumTechnicalSupportPerVenue: value })} /><label className="flex items-center gap-2 text-sm text-slate-600"><input type="checkbox" checked={cbtPolicy.requireSameDay} disabled={!writable} onChange={(event) => updateCbt({ requireSameDay: event.target.checked })} /> Require same day</label><label className="flex items-center gap-2 text-sm text-slate-600"><input type="checkbox" checked={cbtPolicy.allowMultiDay} disabled={!writable} onChange={(event) => updateCbt({ allowMultiDay: event.target.checked })} /> Allow multi-day</label><label className="flex items-center gap-2 text-sm text-slate-600"><input type="checkbox" checked={cbtPolicy.preferMaximumCapacityPerBatch} disabled={!writable} onChange={(event) => updateCbt({ preferMaximumCapacityPerBatch: event.target.checked })} /> Prefer largest capacity</label></div></section>}
      <div className="mt-5 flex flex-wrap gap-2"><Button type="button" disabled={!periodId || busy || !writable} onClick={() => void preview()}>{busy ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : null}Preview calendar</Button><Button type="button" variant="outline" disabled={!periodId || busy || !writable || !days.length} onClick={() => void save()}><Save className="mr-2 h-4 w-4" />Save calendar</Button><Button type="button" variant="outline" disabled={!periodId || busy} onClick={() => void loadCapacity()}>Check feasibility</Button></div>
      {!writable && <p className="mt-3 text-xs text-slate-500">Read-only role: an exam officer or administrator must save changes.</p>}{error && <p role="alert" className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}{message && <p className="mt-4 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-700">{message}</p>}
    </section>
    {capacity && <section className="rounded-xl border border-slate-200 bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Capacity outlook</p><h2 className="mt-1 text-2xl font-bold text-navy">{capacity.status}</h2></div><div className="text-sm text-slate-500">{capacity.summary?.eligibleExamDays ?? 0} eligible days · {capacity.summary?.totalDailyOperatingMinutes ?? 0} minutes</div></div><div className="mt-4 space-y-1 text-sm text-slate-600">{(capacity.blockers ?? []).map((item: Row) => <p key={item.code} className="text-red-700">{item.message}</p>)}{(capacity.suggestions ?? []).map((item: Row, index: number) => <p key={`${item.code ?? "suggestion"}-${index}`}>Suggestion: {item.message ?? item}</p>)}</div></section>}
    {days.length > 0 && <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-card"><div className="border-b border-slate-200 px-5 py-4"><h2 className="font-bold text-navy">Review exam days</h2><p className="mt-1 text-sm text-slate-500">Disable blackouts, adjust hours, or set a day-specific turnaround override.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-400"><tr><th className="px-4 py-3">Date</th><th className="px-4 py-3">Enabled</th><th className="px-4 py-3">Hours</th><th className="px-4 py-3">Turnaround override</th><th className="px-4 py-3">Blackout</th><th className="px-4 py-3">Reason</th></tr></thead><tbody className="divide-y divide-slate-100">{days.map((day, index) => <tr key={day.date}><td className="px-4 py-3 font-semibold text-navy">{day.date}</td><td className="px-4 py-3"><input type="checkbox" checked={day.enabled} disabled={!writable} onChange={(event) => updateDay(index, { enabled: event.target.checked })} /></td><td className="px-4 py-3"><div className="flex gap-2"><input type="time" value={day.startTime} disabled={!writable} onChange={(event) => updateDay(index, { startTime: event.target.value })} className="h-9 rounded border border-slate-200 px-2" /><input type="time" value={day.endTime} disabled={!writable} onChange={(event) => updateDay(index, { endTime: event.target.value })} className="h-9 rounded border border-slate-200 px-2" /></div></td><td className="px-4 py-3"><input type="number" min="0" max="240" value={day.turnaroundMinutesOverride ?? ""} disabled={!writable} placeholder="Default" onChange={(event) => updateDay(index, { turnaroundMinutesOverride: event.target.value === "" ? null : Number(event.target.value) })} className="h-9 w-32 rounded border border-slate-200 px-2" /></td><td className="px-4 py-3"><select value={day.blackoutType ?? ""} disabled={!writable} onChange={(event) => updateDay(index, { blackoutType: event.target.value || null, enabled: event.target.value ? false : day.enabled })} className="h-9 rounded border border-slate-200 px-2">{blackoutOptions.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></td><td className="px-4 py-3"><input value={day.reason ?? ""} disabled={!writable} onChange={(event) => updateDay(index, { reason: event.target.value })} placeholder="Optional" className="h-9 w-full rounded border border-slate-200 px-2" /></td></tr>)}</tbody></table></div></section>}
  </div>;
}

function NumberField({ label, value, disabled, onChange }: { label: string; value: number; disabled: boolean; onChange: (value: number) => void }) { return <label className="text-sm font-semibold text-slate-700">{label}<input type="number" min="0" max="240" value={value} disabled={disabled} onChange={(event) => onChange(Number(event.target.value))} className="mt-2 h-10 w-full rounded-lg border border-slate-200 px-3 font-normal" /></label>; }
function Stat({ label, value }: { label: string; value: string }) { return <div><p className="text-xs uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 font-semibold text-navy">{value}</p></div>; }
