"use client";

import { ChangeEvent, useEffect, useState } from "react";
import Link from "next/link";
import { AlertCircle, ArrowLeft, Check, FileSpreadsheet, Loader2, Upload } from "lucide-react";

import { Button } from "@/components/ui/button";

type Row = Record<string, any>;
function s(value: unknown) { return value == null ? "" : String(value); }

export function RegistrationImportManager({ role }: { role: string }) {
  const writable = ["SUPER_ADMIN", "ADMIN", "EXAM_OFFICER"].includes(role); const [sessions, setSessions] = useState<Row[]>([]); const [semesters, setSemesters] = useState<Row[]>([]); const [sessionId, setSessionId] = useState(""); const [semesterId, setSemesterId] = useState(""); const [file, setFile] = useState<File | null>(null); const [preview, setPreview] = useState<Row | null>(null); const [pending, setPending] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  useEffect(() => { void Promise.all([fetch("/api/academic/sessions?active=true").then((r) => r.json()), fetch("/api/academic/semesters?active=true").then((r) => r.json())]).then(([sessionBody, semesterBody]) => { setSessions(sessionBody.data ?? []); setSemesters(semesterBody.data ?? []); }); }, []);
  async function previewFile() { if (!file || !sessionId || !semesterId) { setError("Select a session, semester, and CSV file first."); return; } setPending(true); setError(""); setNotice(""); try { const csv = await file.text(); const response = await fetch("/api/resources/imports/registrations/preview", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ fileName: file.name, sessionId, semesterId, csv }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message ?? "Unable to preview import."); setPreview(body.data); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to preview import."); } finally { setPending(false); } }
  async function confirmImport() { if (!preview || !file) return; setPending(true); setError(""); try { const summary = preview.summary as Row; const response = await fetch("/api/resources/imports/registrations/confirm", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ fileName: file.name, sessionId, semesterId, rows: preview.rows, duplicateRows: summary.duplicateRows, totalRows: summary.totalRows, invalidRows: summary.invalidRows, confirm: true }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message ?? "Unable to commit import."); setNotice(`Import completed: ${s(body.data.createdRegistrations)} registrations and ${s(body.data.createdStudents)} new students.`); setPreview(null); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to commit import."); } finally { setPending(false); } }
  function onFile(event: ChangeEvent<HTMLInputElement>) { setFile(event.target.files?.[0] ?? null); setPreview(null); setError(""); }
  return <div className="space-y-6"><div><Link href="/examination-data" className="mb-4 inline-flex items-center gap-1.5 text-sm font-semibold text-slate-400 hover:text-teal"><ArrowLeft className="h-4 w-4" />Examination data</Link><p className="mb-2 text-sm font-semibold text-teal">BULK IMPORT</p><h1 className="text-3xl font-bold tracking-tight text-navy">Import registrations</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Upload, validate, review, and explicitly confirm a CSV. No records are written during preview.</p></div>{!writable && <div className="rounded-lg border border-slate-200 bg-white p-4 text-sm text-slate-500">You have read-only access. An examination officer or administrator must run the import.</div>}{(error || notice) && <div role="status" className={`flex gap-2 rounded-lg border p-3 text-sm ${error ? "border-red-200 bg-red-50 text-red-700" : "border-emerald-200 bg-emerald-50 text-emerald-700"}`}>{error ? <AlertCircle className="h-4 w-4" /> : <Check className="h-4 w-4" />}{error || notice}</div>}<section className="rounded-xl border border-slate-200 bg-white p-5 shadow-card"><div className="grid gap-4 md:grid-cols-2"><Select label="Academic session" value={sessionId} options={sessions.map((item) => ({ value: s(item.id), label: s(item.name) }))} onChange={(value) => { setSessionId(value); setSemesterId(""); }} /><Select label="Semester" value={semesterId} options={semesters.filter((item) => !sessionId || s(item.academicSessionId) === sessionId).map((item) => ({ value: s(item.id), label: `${s(item.name)} · ${s((item.academicSession as Row)?.name)}` }))} onChange={setSemesterId} /><label className="md:col-span-2"><span className="text-sm font-semibold text-slate-700">CSV file</span><input disabled={!writable} type="file" accept=".csv,text/csv" onChange={onFile} className="mt-2 block w-full rounded-lg border border-dashed border-slate-300 bg-slate-50 p-3 text-sm" /><span className="mt-2 block text-xs text-slate-400">Required headers: matric_number, student_name, programme, level, course_code. Maximum 10 MB.</span></label></div><Button disabled={!writable || pending} onClick={() => void previewFile()} className="mt-5 gap-2">{pending ? <Loader2 className="h-4 w-4 animate-spin" /> : <Upload className="h-4 w-4" />}Preview CSV</Button></section>{preview && <ImportPreview preview={preview} pending={pending} onConfirm={() => void confirmImport()} />}</div>;
}

function Select({ label, value, options, onChange }: { label: string; value: string; options: { value: string; label: string }[]; onChange: (value: string) => void }) { return <label><span className="text-sm font-semibold text-slate-700">{label}</span><select required value={value} onChange={(event) => onChange(event.target.value)} className="mt-2 h-10 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm outline-none focus:border-teal"><option value="">Select…</option>{options.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label>; }
function ImportPreview({ preview, pending, onConfirm }: { preview: Row; pending: boolean; onConfirm: () => void }) { const summary = preview.summary as Row; const issues = Array.isArray(preview.issues) ? preview.issues as Row[] : []; const rows = Array.isArray(preview.rows) ? preview.rows as Row[] : []; return <section className="rounded-xl border border-teal/20 bg-teal/[0.03] p-5"><div className="flex items-start gap-3"><FileSpreadsheet className="mt-0.5 h-5 w-5 text-teal" /><div><h2 className="font-bold text-navy">Import preview</h2><p className="mt-1 text-sm text-slate-500">Review the summary and row-level validation before committing.</p></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[["Rows", summary.totalRows], ["Valid registrations", summary.validRows], ["New students", summary.newStudents], ["Duplicates", summary.duplicateRows], ["Invalid rows", summary.invalidRows]].map(([label, value]) => <div key={String(label)} className="rounded-lg border border-slate-100 bg-white p-3"><p className="text-xs text-slate-400">{label}</p><p className="mt-1 text-xl font-bold text-navy">{String(value)}</p></div>)}</div>{issues.length > 0 && <div className="mt-5 max-h-56 overflow-y-auto rounded-lg border border-red-100 bg-red-50 p-3">{issues.slice(0, 100).map((issue, index) => <p key={`${s(issue.rowNumber)}-${index}`} className="py-1 text-sm text-red-700"><strong>Row {s(issue.rowNumber)}:</strong> {s(issue.message)}</p>)}</div>}<div className="mt-5 flex items-center justify-between"><p className="text-xs text-slate-500">{rows.length} valid rows are ready for the confirmation transaction.</p><Button disabled={pending || rows.length === 0} onClick={onConfirm} className="gap-2"><Check className="h-4 w-4" />Confirm import</Button></div></section>; }
