import PDFDocument from "pdfkit";
import ExcelJS from "exceljs";
import type { PublicTimetable, PublicTimetableRow } from "@/domain/timetable/public-data";

export type ExportDocument = PublicTimetable & { revisionNumber: number; status: string; publishedAt: string | null };
const institution = "Bamidele Olumilua University of Education, Science and Technology";
const location = "Ikere-Ekiti";
const college = "College of Science";
const csvHeaders = ["Date", "Time", "Course Code", "Course Title", "Programme / Level", "Mode", "Examination Group", "Venue Allocation", "Total Candidates", "Venue Candidates", "Chief Invigilator", "Venue-specific Invigilators", "Staffing Status", "Batch"];
const pdfHeaders = ["Date", "Time", "Course Code", "Programme / Level", "Mode", "Examination Group / Title", "Venue Allocation", "Candidates", "Chief", "Venue Invigilators"];
function modeLabel(mode: string) { return mode === "CBT" ? "CBT" : "Pen on Paper"; }
function staffingLabel(row: PublicTimetableRow) { return row.venueInvigilators.length ? row.venueInvigilators.join("; ") : "Unassigned"; }
function programmeLabel(row: PublicTimetableRow) { return row.programmes.map((p) => `${p.name} / ${p.level}`).join("; "); }
/** Export rows expose only operational data. Student names and registrations are never included. */
export function exportValues(row: PublicTimetableRow, showTotal = true) {
  return [row.date, `${row.startTime} - ${row.endTime}`, row.courseCode, row.courseTitle, programmeLabel(row), modeLabel(row.mode), row.courseCode, `${row.venue} (${row.candidateCount}/${row.totalCandidateCount})`, showTotal ? row.totalCandidateCount : "", row.candidateCount, row.chiefInvigilator ?? "Unassigned", staffingLabel(row), row.staffingStatus, row.batch ?? ""];
}
function exportRows(rows: PublicTimetableRow[]) { const seen = new Set<string>(); return rows.map((row) => { const first = !seen.has(row.eventId); seen.add(row.eventId); return exportValues(row, first); }); }
function csvEscape(value: unknown) { const text = String(value ?? ""); return /[",\r\n]/.test(text) ? `"${text.replaceAll('"', '""')}"` : text; }
export function timetableCsv(data: ExportDocument): Buffer { return Buffer.from(`${[csvHeaders, ...exportRows(data.rows)].map((row) => row.map(csvEscape).join(",")).join("\r\n")}\r\n`, "utf8"); }
function releaseLabel(data: ExportDocument) { return `Revision ${data.revisionNumber} | ${data.status} | ${data.publishedAt ? `Published ${data.publishedAt.slice(0, 10)}` : "Unpublished"}`; }

export async function timetablePdf(data: ExportDocument): Promise<Buffer> {
  const doc = new PDFDocument({ size: "A4", layout: "landscape", margin: 20, bufferPages: true, info: { Title: "BOUESTI Examination Timetable", Author: institution } });
  const chunks: Buffer[] = []; const result = new Promise<Buffer>((resolve, reject) => { doc.on("data", (chunk: Buffer) => chunks.push(chunk)); doc.on("end", () => resolve(Buffer.concat(chunks))); doc.on("error", reject); });
  const contentWidth = doc.page.width - 40; const widths = [58, 66, 70, 92, 60, 102, 105, 55, 65, 128]; let y = 0;
  const wrap = (value: string, width: number) => { const lines: string[] = []; let line = ""; for (const word of value.replace(/[\r\n]+/g, " ").split(/\s+/).filter(Boolean)) { const candidate = line ? `${line} ${word}` : word; if (line && doc.widthOfString(candidate) > width) { lines.push(line); line = word; } else line = candidate; } lines.push(line || ""); return lines; };
  const header = () => { doc.fillColor("#12253f").font("Helvetica-Bold").fontSize(11).text(institution, 20, 18, { width: contentWidth, lineBreak: false }); doc.font("Helvetica").fontSize(8).text(location, 20, 32, { width: contentWidth, lineBreak: false }); doc.font("Helvetica-Bold").fontSize(9).text(college, 20, 44, { width: contentWidth, lineBreak: false }); doc.font("Helvetica").fontSize(8).text(`${data.session} | ${data.semester} | ${data.period}`, 20, 57, { width: contentWidth, lineBreak: false }); doc.text(`${releaseLabel(data)} | Mode: Pen on Paper / CBT`, 20, 69, { width: contentWidth, lineBreak: false }); y = 86; let x = 20; doc.font("Helvetica-Bold").fontSize(7); pdfHeaders.forEach((label, i) => { doc.rect(x, y, widths[i], 28).fill("#e8edf2"); doc.fillColor("#12253f").text(label, x + 3, y + 5, { width: widths[i] - 6, height: 21, lineBreak: false }); x += widths[i]; }); y += 28; doc.font("Helvetica").fontSize(7); };
  const drawRow = (row: PublicTimetableRow, showTotal: boolean) => { const values = [row.date, `${row.startTime} - ${row.endTime}`, row.courseCode, programmeLabel(row), modeLabel(row.mode), `${row.courseCode} / ${row.courseTitle}`, `${row.venue} (${row.candidateCount}/${row.totalCandidateCount})`, showTotal ? `${row.totalCandidateCount} total; ${row.candidateCount} here` : `${row.candidateCount} here`, row.chiefInvigilator ?? "Unassigned", staffingLabel(row)]; const lines = values.map((value, i) => wrap(value, widths[i] - 6)); const height = Math.max(22, Math.max(...lines.map((line) => line.length)) * 9 + 8); if (y + height > doc.page.height - 40) { doc.addPage(); header(); } let x = 20; lines.forEach((cell, i) => { doc.rect(x, y, widths[i], height).lineWidth(0.3).strokeColor("#cbd5e1").stroke(); doc.fillColor("#12253f").text(cell.join("\n"), x + 3, y + 4, { width: widths[i] - 6, height: height - 4, lineGap: 0 }); x += widths[i]; }); y += height; };
  header(); const seen = new Set<string>(); const windows = data.sessionWindows ?? [...new Map(data.rows.map((row) => [`${row.startTime}-${row.endTime}`, { startTime: row.startTime, endTime: row.endTime }])).values()];
  for (const window of windows) { const rows = data.rows.filter((row) => row.startTime === window.startTime && row.endTime === window.endTime); if (y + 22 > doc.page.height - 40) { doc.addPage(); header(); } doc.rect(20, y, contentWidth, 17).fill("#f1f5f9"); doc.fillColor("#12253f").font("Helvetica-Bold").fontSize(7).text(`Session window: ${window.startTime} - ${window.endTime}${rows.length ? "" : " (no examinations assigned)"}`, 24, y + 5, { width: contentWidth - 8, lineBreak: false }); y += 17; for (const row of rows) { const first = !seen.has(row.eventId); seen.add(row.eventId); drawRow(row, first); } }
  if (!data.rows.length) doc.fillColor("#12253f").font("Helvetica").fontSize(8).text("No examinations match these filters.", 20, y + 10, { lineBreak: false });
  const pages = doc.bufferedPageRange(); for (let i = 0; i < pages.count; i += 1) { doc.switchToPage(i); doc.fillColor("#12253f").font("Helvetica").fontSize(7).text(`Page ${i + 1} of ${pages.count}`, 20, doc.page.height - 22, { width: contentWidth, height: 10, align: "right", lineBreak: false }); } doc.end(); return result;
}

export async function timetableExcel(data: ExportDocument, diagnostics?: { code: string; message: string }[]): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook(); workbook.creator = institution; workbook.subject = `${data.period} - Revision ${data.revisionNumber}`;
  const add = (name: string, rows: PublicTimetableRow[]) => { const sheet = workbook.addWorksheet(name, { views: [{ state: "frozen", ySplit: 4 }], pageSetup: { orientation: "landscape", fitToPage: true, fitToWidth: 1, fitToHeight: 0, paperSize: 9 } }); sheet.mergeCells("A1:N1"); sheet.getCell("A1").value = institution; sheet.getCell("A1").font = { bold: true, size: 14, color: { argb: "FF12253F" } }; sheet.mergeCells("A2:N2"); sheet.getCell("A2").value = `${location} | ${college}`; sheet.mergeCells("A3:N3"); sheet.getCell("A3").value = `${data.session} | ${data.semester} | ${data.period} | ${releaseLabel(data)} | Mode: Pen on Paper / CBT`; sheet.addRow(csvHeaders); sheet.getRow(4).font = { bold: true, color: { argb: "FFFFFFFF" } }; sheet.getRow(4).fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF12253F" } }; exportRows(rows).forEach((row) => sheet.addRow(row)); sheet.columns.forEach((column, i) => { column.width = [14, 20, 18, 32, 38, 16, 18, 34, 16, 16, 20, 30, 16, 10][i]; }); sheet.autoFilter = { from: { row: 4, column: 1 }, to: { row: Math.max(4, sheet.rowCount), column: csvHeaders.length } }; sheet.pageSetup.printTitlesRow = "1:4"; sheet.eachRow((row, index) => { if (index >= 4) { row.eachCell((cell) => { cell.alignment = { vertical: "top", wrapText: true }; cell.border = { top: { style: "thin", color: { argb: "FFCBD5E1" } }, bottom: { style: "thin", color: { argb: "FFCBD5E1" } } }; }); row.height = index === 4 ? 32 : 34; } }); return sheet; };
  add("Full Timetable", data.rows); add("Programme View", [...data.rows].sort((a, b) => (a.programmes[0]?.name ?? "").localeCompare(b.programmes[0]?.name ?? "") || a.date.localeCompare(b.date))); add("Venue View", [...data.rows].sort((a, b) => a.venue.localeCompare(b.venue) || a.date.localeCompare(b.date))); add("CBT Batches", data.rows.filter((row) => row.mode === "CBT"));
  const sessions = workbook.addWorksheet("Session Windows", { views: [{ state: "frozen", ySplit: 1 }] }); sessions.addRow(["Session window", "Allocated examinations", "Status"]); sessions.getRow(1).font = { bold: true }; for (const window of data.sessionWindows ?? []) { const count = data.rows.filter((row) => row.startTime === window.startTime && row.endTime === window.endTime).length; sessions.addRow([`${window.startTime} - ${window.endTime}`, count, count ? "Assigned" : "Empty approved session"]); } sessions.getColumn(1).width = 24; sessions.getColumn(2).width = 24; sessions.getColumn(3).width = 28;
  if (diagnostics) { const sheet = workbook.addWorksheet("Diagnostics", { views: [{ state: "frozen", ySplit: 1 }] }); sheet.addRow(["Code", "Message"]); sheet.getRow(1).font = { bold: true }; diagnostics.forEach((diagnostic) => sheet.addRow([diagnostic.code, diagnostic.message])); sheet.getColumn(1).width = 40; sheet.getColumn(2).width = 100; sheet.getColumn(2).alignment = { wrapText: true }; }
  return Buffer.from(await workbook.xlsx.writeBuffer());
}
