import { Prisma } from "@prisma/client";
import { assessPlannerFeasibility, generateCalendarProposal, validatePlannerDay, type PlannerDay, type PlannerPolicy } from "@/domain/timetable";
import { prisma } from "@/lib/prisma";
import { AcademicError } from "@/server/academic/errors";
import { buildAggregateSchedulingDataset } from "./aggregate-dataset-builder";
import type { plannerPreviewRequest, plannerSaveRequest } from "./schemas";

type PreviewInput = typeof plannerPreviewRequest._type;
type SaveInput = typeof plannerSaveRequest._type;
function parseDate(value: string) { const date = new Date(`${value}T00:00:00.000Z`); return Number.isNaN(date.getTime()) || date.toISOString().slice(0, 10) !== value ? null : date; }
function dateKey(value: Date) { return value.toISOString().slice(0, 10); }
function assertPolicy(policy: PlannerPolicy) { if (!Number.isFinite(timeToMinutes(policy.defaultDayStartTime)) || !Number.isFinite(timeToMinutes(policy.defaultDayEndTime)) || timeToMinutes(policy.defaultDayStartTime) >= timeToMinutes(policy.defaultDayEndTime)) throw new AcademicError("INVALID_CALENDAR_CONFIGURATION", "The default day opening time must be before the closing time.", {}, 400); if (policy.timeGranularityMinutes <= 0) throw new AcademicError("INVALID_CALENDAR_CONFIGURATION", "Time granularity must be positive.", {}, 400); }
function assertDateRange(startValue: string, endValue: string) { const start = parseDate(startValue); const end = parseDate(endValue); if (!start || !end || start > end) throw new AcademicError("INVALID_CALENDAR_CONFIGURATION", "Provide a valid calendar date range.", {}, 400); }
function timeToMinutes(value: string) { if (!/^([01]\d|2[0-3]):[0-5]\d$/.test(value)) return Number.NaN; const [hour, minute] = value.split(":").map(Number); return hour * 60 + minute; }
async function periodFor(examPeriodId: string) { const period = await prisma.examPeriod.findUnique({ where: { id: examPeriodId }, include: { calendarDays: { orderBy: { date: "asc" } } } }); if (!period) throw new AcademicError("NOT_FOUND", "The examination period was not found.", { examPeriodId }, 404); return period; }
function assertDatesInsidePeriod(values: string[], period: Awaited<ReturnType<typeof periodFor>>) { const start = dateKey(period.startDate); const end = dateKey(period.endDate); if (values.some((value) => value < start || value > end)) throw new AcademicError("CALENDAR_DATE_OUTSIDE_PERIOD", "Every calendar day must fall inside the examination period.", { startDate: start, endDate: end }, 400); }
function assertSelectedDates(input: PreviewInput, period: Awaited<ReturnType<typeof periodFor>>) { if (input.mode !== "SELECTED_DATES") return; const selected = input.selectedDates ?? []; if (!selected.length || selected.some((value) => !parseDate(value))) throw new AcademicError("INVALID_CALENDAR_CONFIGURATION", "Select at least one valid examination date.", {}, 400); assertDatesInsidePeriod([...new Set(selected)], period); }
function policyFor(period: Awaited<ReturnType<typeof periodFor>>): PlannerPolicy { return { defaultDayStartTime: period.defaultDayStartTime, defaultDayEndTime: period.defaultDayEndTime, defaultTurnaroundMinutes: period.defaultTurnaroundMinutes, writtenTurnaroundMinutes: period.writtenTurnaroundMinutes, cbtTurnaroundMinutes: period.cbtTurnaroundMinutes, timeGranularityMinutes: period.timeGranularityMinutes, weekdays: [false, true, true, true, true, true, false] }; }
function mapDay(day: Awaited<ReturnType<typeof periodFor>>["calendarDays"][number]): PlannerDay { return { date: dateKey(day.date), enabled: day.enabled, dayType: day.dayType, startTime: day.startTime, endTime: day.endTime, turnaroundMinutesOverride: day.turnaroundMinutesOverride, blackoutType: day.blackoutType as PlannerDay["blackoutType"], reason: day.reason }; }

export async function getPlanner(examPeriodId: string) { const period = await periodFor(examPeriodId); return { period: { id: period.id, name: period.name, startDate: dateKey(period.startDate), endDate: dateKey(period.endDate), defaultDayStartTime: period.defaultDayStartTime, defaultDayEndTime: period.defaultDayEndTime, defaultTurnaroundMinutes: period.defaultTurnaroundMinutes, writtenTurnaroundMinutes: period.writtenTurnaroundMinutes, cbtTurnaroundMinutes: period.cbtTurnaroundMinutes, timeGranularityMinutes: period.timeGranularityMinutes, cbtBatchingEnabled: period.cbtBatchingEnabled, cbtMinimumBatchGapMinutes: period.cbtMinimumBatchGapMinutes, cbtMaxBatchesPerDay: period.cbtMaxBatchesPerDay, cbtRequireSameDay: period.cbtRequireSameDay, cbtAllowMultiDay: period.cbtAllowMultiDay, cbtPreferMaximumCapacityPerBatch: period.cbtPreferMaximumCapacityPerBatch, cbtMinimumInvigilatorsPerVenue: period.cbtMinimumInvigilatorsPerVenue, cbtMinimumTechnicalSupportPerVenue: period.cbtMinimumTechnicalSupportPerVenue, cbtAdditionalSupportPerCandidates: period.cbtAdditionalSupportPerCandidates }, days: period.calendarDays.map(mapDay) }; }

export async function previewPlanner(input: PreviewInput) { const period = await periodFor(input.examPeriodId); const policy = input.policy as PlannerPolicy; assertPolicy(policy); assertDateRange(input.startDate, input.endDate); assertSelectedDates(input, period); const proposal = generateCalendarProposal({ mode: input.mode, startDate: input.startDate, endDate: input.endDate, selectedDates: input.selectedDates, policy }); if (!proposal.length) throw new AcademicError("INVALID_CALENDAR_CONFIGURATION", "The planner did not produce any calendar days.", {}, 400); assertDatesInsidePeriod(proposal.map((day) => day.date), period); const invalid = proposal.filter((day) => validatePlannerDay(day, policy.timeGranularityMinutes)); if (invalid.length) throw new AcademicError("INVALID_CALENDAR_CONFIGURATION", "One or more proposed calendar days have invalid hours or granularity.", { dates: invalid.map((day) => day.date) }, 400); return { period: { id: period.id, name: period.name }, days: proposal, summary: { calendarDays: proposal.length, examDays: proposal.filter((day) => day.enabled).length, excludedDays: proposal.filter((day) => !day.enabled).length, defaultHours: `${policy.defaultDayStartTime}-${policy.defaultDayEndTime}`, turnaroundMinutes: policy.defaultTurnaroundMinutes } }; }

export async function savePlanner(input: SaveInput, actorId: string) { const period = await periodFor(input.examPeriodId); const policy = input.policy as PlannerPolicy; assertPolicy(policy); assertDateRange(input.startDate, input.endDate); assertSelectedDates(input, period); const invalid = input.days.filter((day) => validatePlannerDay(day, policy.timeGranularityMinutes)); if (invalid.length) throw new AcademicError("INVALID_CALENDAR_CONFIGURATION", "One or more calendar days have invalid hours or granularity.", { dates: invalid.map((day) => day.date) }, 400); const dates = input.days.map((day) => parseDate(day.date)); const dateKeys = input.days.map((day) => day.date); if (dates.some((date) => !date)) throw new AcademicError("INVALID_CALENDAR_CONFIGURATION", "One or more calendar days are invalid.", {}, 400); if (new Set(dateKeys).size !== dateKeys.length) throw new AcademicError("INVALID_CALENDAR_CONFIGURATION", "Calendar days cannot contain duplicate dates.", {}, 400); assertDatesInsidePeriod(dateKeys, period); const referenced = await prisma.timetableGeneration.count({ where: { periodId: period.id, status: { in: ["COMPLETED", "COMPLETED_WITH_WARNINGS"] } } }); if (referenced && input.mode !== "SELECTED_DATES") throw new AcademicError("CALENDAR_ALREADY_REFERENCED", "This period already has generated output; create a new draft period before replacing its calendar.", {}, 409);
  await prisma.$transaction(async (db) => { await db.examPeriod.update({ where: { id: period.id }, data: { defaultDayStartTime: policy.defaultDayStartTime, defaultDayEndTime: policy.defaultDayEndTime, defaultTurnaroundMinutes: policy.defaultTurnaroundMinutes, writtenTurnaroundMinutes: policy.writtenTurnaroundMinutes, cbtTurnaroundMinutes: policy.cbtTurnaroundMinutes, timeGranularityMinutes: policy.timeGranularityMinutes, cbtBatchingEnabled: policy.cbtBatchingEnabled ?? period.cbtBatchingEnabled, cbtMinimumBatchGapMinutes: policy.cbtMinimumBatchGapMinutes ?? period.cbtMinimumBatchGapMinutes, cbtMaxBatchesPerDay: policy.cbtMaxBatchesPerDay === undefined ? period.cbtMaxBatchesPerDay : policy.cbtMaxBatchesPerDay, cbtRequireSameDay: policy.cbtRequireSameDay ?? period.cbtRequireSameDay, cbtAllowMultiDay: policy.cbtAllowMultiDay ?? period.cbtAllowMultiDay, cbtPreferMaximumCapacityPerBatch: policy.cbtPreferMaximumCapacityPerBatch ?? period.cbtPreferMaximumCapacityPerBatch, cbtMinimumInvigilatorsPerVenue: policy.cbtMinimumInvigilatorsPerVenue ?? period.cbtMinimumInvigilatorsPerVenue, cbtMinimumTechnicalSupportPerVenue: policy.cbtMinimumTechnicalSupportPerVenue ?? period.cbtMinimumTechnicalSupportPerVenue, cbtAdditionalSupportPerCandidates: policy.cbtAdditionalSupportPerCandidates === undefined ? period.cbtAdditionalSupportPerCandidates : policy.cbtAdditionalSupportPerCandidates } }); await db.examCalendarDay.deleteMany({ where: { examPeriodId: period.id } }); await db.examCalendarDay.createMany({ data: input.days.map((day) => ({ examPeriodId: period.id, date: parseDate(day.date)!, enabled: day.enabled, dayType: day.dayType, startTime: day.startTime, endTime: day.endTime, turnaroundMinutesOverride: day.turnaroundMinutesOverride ?? null, blackoutType: day.blackoutType as any ?? null, reason: day.reason ?? null })) }); await db.auditLog.create({ data: { actorId, action: "EXAM_CALENDAR_SAVED", entity: "ExamPeriod", entityId: period.id, metadata: { mode: input.mode, days: input.days.length } as Prisma.InputJsonValue } }); }, { timeout: 60000 }); return getPlanner(period.id);
}

export async function getPlannerCapacity(examPeriodId: string) { const period = await periodFor(examPeriodId); const dataset = await buildAggregateSchedulingDataset(period.sessionId, period.semesterId, examPeriodId, {}, "FLEXIBLE_INTERVALS"); const days = (dataset.calendarDays ?? []).map((day) => ({ ...day, blackoutType: day.blackoutType as PlannerDay["blackoutType"] })); return assessPlannerFeasibility(days, dataset.events, dataset.venues, dataset.conflictGraph, dataset.cbtBatchingPolicy?.enabled); }
