import type { CandidateTimetable, ConstraintViolation, SchedulingDataset } from "../types";

function overlap(a: { date: string; startTime: string; endTime: string }, b: { date: string; startTime: string; endTime: string }) { return a.date === b.date && a.startTime < b.endTime && b.startTime < a.endTime; }
function courseStudents(dataset: SchedulingDataset) { const map = new Map<string, Set<string>>(); for (const registration of dataset.registrations) { const set = map.get(registration.courseId) ?? new Set<string>(); set.add(registration.studentId); map.set(registration.courseId, set); } return map; }

export function validateHardConstraints(timetable: CandidateTimetable, dataset: SchedulingDataset): ConstraintViolation[] {
  const violations: ConstraintViolation[] = []; const students = courseStudents(dataset); const slots = new Map(dataset.timeSlots.map((slot) => [slot.id, slot])); const courses = new Map(dataset.courses.map((course) => [course.id, course])); const venues = new Map(dataset.venues.map((venue) => [venue.id, venue])); const invigilators = new Map(dataset.invigilators.map((invigilator) => [invigilator.id, invigilator]));
  const assignments = timetable.assignments;
  for (const assignment of assignments) {
    const slot = slots.get(assignment.timeSlotId); const course = courses.get(assignment.courseId);
    if (!slot || slot.examPeriodId !== dataset.examPeriod.id) violations.push({ code: "INVALID_TIME_SLOT", message: "Assignment uses a time slot outside the selected examination period.", metadata: { courseId: assignment.courseId, timeSlotId: assignment.timeSlotId } });
    if (!course || !course.active) violations.push({ code: "INACTIVE_COURSE", message: "Inactive or missing course was assigned.", metadata: { courseId: assignment.courseId } });
    if (!slot || !course) continue;
    const candidateCount = students.get(course.id)?.size ?? course.estimatedStudentCount;
    const totalCapacity = assignment.venues.reduce((sum, venueAssignment) => sum + (venues.get(venueAssignment.venueId)?.capacity ?? 0), 0);
    if (totalCapacity < candidateCount) violations.push({ code: "INSUFFICIENT_VENUE_CAPACITY", message: "Assigned venues cannot seat all registered candidates.", metadata: { courseId: course.id, candidateCount, totalCapacity } });
    if (new Set(assignment.venues.map((venue) => venue.venueId)).size !== assignment.venues.length) violations.push({ code: "DUPLICATE_VENUE", message: "An examination cannot assign the same venue more than once.", metadata: { courseId: course.id } });
    if (new Set(assignment.invigilators.map((invigilator) => invigilator.invigilatorId)).size !== assignment.invigilators.length) violations.push({ code: "DUPLICATE_INVIGILATOR", message: "An examination cannot assign the same invigilator more than once.", metadata: { courseId: course.id } });
    for (const venueAssignment of assignment.venues) { const venue = venues.get(venueAssignment.venueId); if (!venue || !venue.active) violations.push({ code: "INACTIVE_VENUE", message: "Inactive or missing venue was assigned.", metadata: { venueId: venueAssignment.venueId } }); if (venue && dataset.venueUnavailability.some((period) => period.resourceId === venue.id && overlap(slot, period))) violations.push({ code: "VENUE_UNAVAILABLE", message: "Venue is unavailable during the assigned slot.", metadata: { venueId: venue.id, timeSlotId: slot.id } }); }
    for (const invigilatorAssignment of assignment.invigilators) { const invigilator = invigilators.get(invigilatorAssignment.invigilatorId); if (!invigilator || !invigilator.active) violations.push({ code: "INACTIVE_INVIGILATOR", message: "Inactive or missing invigilator was assigned.", metadata: { invigilatorId: invigilatorAssignment.invigilatorId } }); if (invigilator && dataset.invigilatorUnavailability.some((period) => period.resourceId === invigilator.id && overlap(slot, period))) violations.push({ code: "INVIGILATOR_UNAVAILABLE", message: "Invigilator is unavailable during the assigned slot.", metadata: { invigilatorId: invigilator.id, timeSlotId: slot.id } }); }
  }
  for (let i = 0; i < assignments.length; i += 1) for (let j = i + 1; j < assignments.length; j += 1) { const a = assignments[i]; const b = assignments[j]; const slotA = slots.get(a.timeSlotId); const slotB = slots.get(b.timeSlotId); if (!slotA || !slotB || !overlap(slotA, slotB)) continue; const shared = [...(students.get(a.courseId) ?? [])].filter((studentId) => students.get(b.courseId)?.has(studentId)); if (shared.length) violations.push({ code: "STUDENT_CLASH", message: "Courses with shared students overlap.", metadata: { courseA: a.courseId, courseB: b.courseId, sharedStudentCount: shared.length, timeSlot: slotA.id } }); for (const venueA of a.venues) if (b.venues.some((venueB) => venueA.venueId === venueB.venueId)) violations.push({ code: "VENUE_CLASH", message: "A venue is assigned to simultaneous examinations.", metadata: { venueId: venueA.venueId, timeSlot: slotA.id } }); for (const invA of a.invigilators) if (b.invigilators.some((invB) => invA.invigilatorId === invB.invigilatorId)) violations.push({ code: "INVIGILATOR_CLASH", message: "An invigilator is assigned to simultaneous examinations.", metadata: { invigilatorId: invA.invigilatorId, timeSlot: slotA.id } }); }
  return violations;
}
