import { intervalsOverlap, makeInterval, minutesToTime, timeToMinutes, type TimeInterval } from "../intervals";
import { resolveAggregateGenerationConfig } from "./config";
import { generateAggregateTimetable } from "./engine";
import { generateFlexibleAggregateTimetable } from "./flexible-engine";
import type { AggregateCandidateTimetable, AggregateConstraintViolation, AggregateExamAssignment, AggregateGenerationConfig, AggregateSchedulingDataset, AggregateTimeSlot, AggregateUnavailablePeriod, AggregateVenue, CbtBatchingPolicy, CbtSitting, CbtSittingStaffAssignment, CbtSittingVenueAssignment, CbtStaffingPolicy, SchedulingExamEvent, UnscheduledAggregateEvent } from "./types";

const defaultBatching: CbtBatchingPolicy = { enabled: false, minimumBatchGapMinutes: 30, maxBatchesPerDay: null, requireSameDay: true, allowMultiDay: false, preferMaximumCapacityPerBatch: true };
const defaultStaffing: CbtStaffingPolicy = { minimumInvigilatorsPerVenue: 1, minimumTechnicalSupportPerVenue: 1, additionalSupportPerCandidates: null };

export type CbtBatchPreview = { eventId: string; candidateCount: number; effectiveConcurrentCapacity: number; requiredBatches: number; candidateCounts: number[]; batchingEnabled: boolean; status: "READY" | "BLOCKED" };
export type CbtGenerationResult = { candidate: AggregateCandidateTimetable; previews: CbtBatchPreview[] };

export function calculateRequiredBatches(candidateCount: number, effectiveConcurrentCapacity: number) { return candidateCount > 0 && effectiveConcurrentCapacity > 0 ? Math.ceil(candidateCount / effectiveConcurrentCapacity) : 0; }

export function splitCandidateCounts(candidateCount: number, capacity: number) { if (candidateCount <= 0 || capacity <= 0) return []; const counts: number[] = []; let remaining = candidateCount; while (remaining > 0) { const count = Math.min(capacity, remaining); counts.push(count); remaining -= count; } return counts; }

function policy(dataset: AggregateSchedulingDataset) { return { ...defaultBatching, ...(dataset.cbtBatchingPolicy ?? {}) }; }
function staffing(dataset: AggregateSchedulingDataset) { return { ...defaultStaffing, ...(dataset.cbtStaffingPolicy ?? {}) }; }
function cbtTurnaround(dataset: AggregateSchedulingDataset, date: string) { return dataset.calendarDays?.find((day) => day.date === date)?.turnaroundMinutesOverride ?? dataset.timePolicy?.cbtTurnaroundMinutes ?? 15; }
function cbtVenues(dataset: AggregateSchedulingDataset) { return dataset.venues.filter((venue) => venue.active && (venue.capability === "CBT" || venue.capability === "BOTH") && (venue.usableComputerCapacity ?? 0) > 0); }
function capacity(venues: AggregateVenue[]) { return venues.reduce((sum, venue) => sum + (venue.usableComputerCapacity ?? 0), 0); }
function intervalForAssignment(assignment: AggregateExamAssignment, dataset: AggregateSchedulingDataset) { if (dataset.schedulingMode === "FLEXIBLE_INTERVALS") return makeInterval(assignment.date, timeToMinutes(assignment.startTime), timeToMinutes(assignment.endTime)); const slot = dataset.timeSlots.find((item) => item.id === assignment.timeSlotId); return slot ? makeInterval(slot.date, timeToMinutes(slot.startTime), timeToMinutes(slot.endTime)) : null; }
function unavailable(interval: TimeInterval, resourceId: string, periods: AggregateUnavailablePeriod[], extra = 0) { return periods.some((period) => { if (period.resourceId !== resourceId) return false; const blocked = makeInterval(period.date, timeToMinutes(period.startTime), timeToMinutes(period.endTime)); return blocked ? intervalsOverlap({ ...interval, endMinutes: interval.endMinutes + extra }, blocked) : false; }); }
function occupied(interval: TimeInterval, resourceId: string, resources: Array<{ interval: TimeInterval; ids: string[] }>) { return resources.some((item) => item.ids.includes(resourceId) && intervalsOverlap(interval, item.interval)); }
function allocateCandidates(count: number, venues: AggregateVenue[], preferMaximum: boolean): CbtSittingVenueAssignment[] | null { const sorted = venues.slice().sort((a, b) => preferMaximum ? (b.usableComputerCapacity ?? 0) - (a.usableComputerCapacity ?? 0) || a.code.localeCompare(b.code) : a.code.localeCompare(b.code)); const selected: CbtSittingVenueAssignment[] = []; let remaining = count; for (const venue of sorted) { if (remaining <= 0) break; const cap = venue.usableComputerCapacity ?? 0; const assigned = Math.min(cap, remaining); if (assigned > 0) { selected.push({ venueId: venue.id, allocatedCandidates: assigned, allocatedCapacity: cap }); remaining -= assigned; } } return remaining === 0 ? selected : null; }
function eventConflicts(event: SchedulingExamEvent, interval: TimeInterval, eventIntervals: Map<string, TimeInterval[]>, dataset: AggregateSchedulingDataset) { return dataset.conflictGraph.edges.filter((edge) => edge.hard && (edge.eventAId === event.id || edge.eventBId === event.id)).some((edge) => { const otherId = edge.eventAId === event.id ? edge.eventBId : edge.eventAId; return (eventIntervals.get(otherId) ?? []).some((other) => intervalsOverlap(interval, other)); }); }
function slots(dataset: AggregateSchedulingDataset, durationMinutes: number) { return dataset.schedulingMode === "FLEXIBLE_INTERVALS" ? (dataset.calendarDays ?? []).filter((day) => day.enabled && !day.blackoutType).flatMap((day) => { const start = timeToMinutes(day.startTime); const end = timeToMinutes(day.endTime); const granularity = dataset.timePolicy?.timeGranularityMinutes ?? 30; const result: AggregateTimeSlot[] = []; for (let value = start; value + durationMinutes <= end; value += granularity) result.push({ id: `flex-${day.date}-${value}`, examPeriodId: dataset.examPeriod.id, date: day.date, startTime: minutesToTime(value) ?? "", endTime: minutesToTime(value + durationMinutes) ?? day.endTime }); return result; }) : dataset.timeSlots.slice(); }
function baseOccupancy(candidate: AggregateCandidateTimetable, dataset: AggregateSchedulingDataset) { return candidate.assignments.flatMap((assignment) => { const interval = intervalForAssignment(assignment, dataset); return interval ? [{ interval, ids: assignment.venues.map((item) => item.venueId) }, { interval, ids: assignment.invigilators.map((item) => item.invigilatorId) }] : []; }); }

export function scheduleCbtEvent(event: SchedulingExamEvent, dataset: AggregateSchedulingDataset, base: AggregateCandidateTimetable, _config: AggregateGenerationConfig): { sittings: CbtSitting[]; violation?: AggregateConstraintViolation } {
  const batching = policy(dataset); const staffPolicy = staffing(dataset); const allVenues = cbtVenues(dataset); const maxCapacity = capacity(allVenues); const required = calculateRequiredBatches(event.candidateCount, maxCapacity);
  if (!batching.enabled && event.candidateCount > maxCapacity) return { sittings: [], violation: { code: "CBT_BATCHING_DISABLED_FOR_OVERSIZED_EVENT", message: "CBT batching is disabled for an event larger than simultaneous usable computer capacity.", metadata: { eventId: event.id, candidateCount: event.candidateCount, capacity: maxCapacity } } };
  if (!maxCapacity) return { sittings: [], violation: { code: "NO_USABLE_CBT_CAPACITY", message: "No usable CBT computer capacity is available.", metadata: { eventId: event.id } } };
  const counts = splitCandidateCounts(event.candidateCount, maxCapacity); const windows = slots(dataset, event.durationMinutes).sort((a, b) => `${a.date}|${a.startTime}|${a.id}`.localeCompare(`${b.date}|${b.startTime}|${b.id}`)); const occupancy = baseOccupancy(base, dataset); const eventIntervals = new Map<string, TimeInterval[]>(); for (const assignment of base.assignments) { const interval = intervalForAssignment(assignment, dataset); if (interval) eventIntervals.set(assignment.eventId, [...(eventIntervals.get(assignment.eventId) ?? []), interval]); } const selected: CbtSitting[] = []; const dates = new Set<string>(); const staffCounts = new Map<string, number>();
  // Seed occupancy and workload from previously placed CBT events.
  for (const sitting of base.sittings ?? []) {
    const interval = makeInterval(sitting.date, timeToMinutes(sitting.startTime), timeToMinutes(sitting.endTime));
    if (!interval) continue;
    occupancy.push({ interval: { ...interval, endMinutes: interval.endMinutes + cbtTurnaround(dataset, interval.date) }, ids: sitting.venues.map((v) => v.venueId) }, { interval, ids: sitting.staff.map((s) => s.staffId) });
    eventIntervals.set(sitting.eventId, [...(eventIntervals.get(sitting.eventId) ?? []), interval]);
    for (const person of sitting.staff) { const key = person.staffId + "|" + sitting.date; staffCounts.set(key, (staffCounts.get(key) ?? 0) + 1); }
  }
  for (const assignment of base.assignments) for (const person of assignment.invigilators) {
    const key = person.invigilatorId + "|" + intervalForAssignment(assignment, dataset)?.date;
    staffCounts.set(key, (staffCounts.get(key) ?? 0) + 1);
  }
  for (const count of counts) {
    let placed: CbtSitting | undefined;
    for (const slot of windows) {
      const start = timeToMinutes(slot.startTime); const slotEnd = timeToMinutes(slot.endTime); const interval = makeInterval(slot.date, start, start + event.durationMinutes); if (!interval || (dataset.schedulingMode !== "FLEXIBLE_INTERVALS" && start + event.durationMinutes > slotEnd)) continue;
      if (batching.requireSameDay && dates.size && !dates.has(slot.date)) continue; if (!batching.allowMultiDay && dates.size && !dates.has(slot.date)) continue;
      if ((batching.maxBatchesPerDay ?? Infinity) <= selected.filter((item) => item.date === slot.date).length) continue;
      const previous = selected[selected.length - 1]; if (previous && slot.date < previous.date) continue; if (previous && previous.date === slot.date && start < timeToMinutes(previous.endTime) + batching.minimumBatchGapMinutes) continue; if (eventConflicts(event, interval, eventIntervals, dataset)) continue;
      const availableVenues = allVenues.filter((venue) => !unavailable(interval, venue.id, dataset.venueUnavailability, dataset.schedulingMode === "FLEXIBLE_INTERVALS" ? cbtTurnaround(dataset, interval.date) : dataset.timePolicy?.cbtTurnaroundMinutes ?? 15) && !occupied({ ...interval, endMinutes: interval.endMinutes + cbtTurnaround(dataset, interval.date) }, venue.id, occupancy)); const venueAssignments = allocateCandidates(count, availableVenues, batching.preferMaximumCapacityPerBatch); if (!venueAssignments) continue;
      const requiredInvigilators = venueAssignments.length * staffPolicy.minimumInvigilatorsPerVenue; const requiredSupport = venueAssignments.length * staffPolicy.minimumTechnicalSupportPerVenue + (staffPolicy.additionalSupportPerCandidates ? Math.ceil(count / staffPolicy.additionalSupportPerCandidates) : 0);
      const availableInvigilators = dataset.invigilators.filter((item) => item.active && item.role !== "CBT_TECHNICAL_SUPPORT" && !unavailable(interval, item.id, dataset.invigilatorUnavailability) && !occupied(interval, item.id, occupancy) && (item.maximumDailyAssignments == null || (staffCounts.get(`${item.id}|${slot.date}`) ?? 0) < item.maximumDailyAssignments)).sort((a, b) => a.name.localeCompare(b.name) || a.id.localeCompare(b.id)); const availableSupport = dataset.invigilators.filter((item) => item.active && item.role === "CBT_TECHNICAL_SUPPORT" && !unavailable(interval, item.id, dataset.invigilatorUnavailability) && !occupied(interval, item.id, occupancy) && (item.maximumDailyAssignments == null || (staffCounts.get(`${item.id}|${slot.date}`) ?? 0) < item.maximumDailyAssignments)).sort((a, b) => a.name.localeCompare(b.name) || a.id.localeCompare(b.id)); if (availableInvigilators.length < requiredInvigilators) continue; if (availableSupport.length < requiredSupport) continue;
      const staff: CbtSittingStaffAssignment[] = [...availableInvigilators.slice(0, requiredInvigilators).map((item, index) => ({ staffId: item.id, assignmentType: "INVIGILATOR" as const, venueId: venueAssignments[index % venueAssignments.length]?.venueId })), ...availableSupport.slice(0, requiredSupport).map((item, index) => ({ staffId: item.id, assignmentType: "TECHNICAL_SUPPORT" as const, venueId: venueAssignments[index % venueAssignments.length]?.venueId }))]; placed = { eventId: event.id, sequenceNumber: selected.length + 1, batchLabel: String.fromCharCode(65 + selected.length), candidateCount: count, date: interval.date, startTime: minutesToTime(interval.startMinutes)!, endTime: minutesToTime(interval.endMinutes)!, venues: venueAssignments, staff }; break;
    }
    if (!placed) return { sittings: [], violation: { code: selected.length ? (batching.requireSameDay ? "SAME_DAY_BATCH_REQUIREMENT_UNSATISFIED" : "NO_FEASIBLE_CBT_BATCH_WINDOW") : "NO_FEASIBLE_CBT_BATCH_WINDOW", message: "No feasible CBT sitting window satisfies capacity, gap, venue, conflict, and staffing constraints.", metadata: { eventId: event.id, requiredBatches: required, scheduledBatches: selected.length } } };
    selected.push(placed); dates.add(placed.date); const interval = makeInterval(placed.date, timeToMinutes(placed.startTime), timeToMinutes(placed.endTime))!; occupancy.push({ interval: { ...interval, endMinutes: interval.endMinutes + cbtTurnaround(dataset, interval.date) }, ids: placed.venues.map((item) => item.venueId) }, { interval, ids: placed.staff.map((item) => item.staffId) }); eventIntervals.set(event.id, [...(eventIntervals.get(event.id) ?? []), interval]); placed.staff.forEach((item) => staffCounts.set(`${item.staffId}|${placed.date}`, (staffCounts.get(`${item.staffId}|${placed.date}`) ?? 0) + 1));
  }
  return { sittings: selected };
}

function previewFor(event: SchedulingExamEvent, dataset: AggregateSchedulingDataset): CbtBatchPreview { const available = cbtVenues(dataset); const effectiveCapacity = capacity(available); const requiredBatches = calculateRequiredBatches(event.candidateCount, effectiveCapacity); const batching = policy(dataset); return { eventId: event.id, candidateCount: event.candidateCount, effectiveConcurrentCapacity: effectiveCapacity, requiredBatches, candidateCounts: splitCandidateCounts(event.candidateCount, effectiveCapacity), batchingEnabled: batching.enabled, status: !effectiveCapacity || (!batching.enabled && event.candidateCount > effectiveCapacity) ? "BLOCKED" : "READY" }; }

export function previewCbtBatches(dataset: AggregateSchedulingDataset) { return dataset.events.filter((event) => event.examMode === "CBT").map((event) => previewFor(event, dataset)); }

export function generateCbtBatchedAggregateTimetable(dataset: AggregateSchedulingDataset, inputConfig: Partial<AggregateGenerationConfig> = {}): CbtGenerationResult {
  const config = resolveAggregateGenerationConfig(inputConfig); const nonCbt = dataset.events.filter((event) => event.examMode !== "CBT"); const baseDataset = { ...dataset, events: nonCbt }; const base = dataset.schedulingMode === "FLEXIBLE_INTERVALS" ? generateFlexibleAggregateTimetable(baseDataset, config) : generateAggregateTimetable(baseDataset, config); const sittings: CbtSitting[] = []; const failures: UnscheduledAggregateEvent[] = []; const cbtEvents = dataset.events.filter((event) => event.examMode === "CBT").sort((a, b) => a.id.localeCompare(b.id)); for (const event of cbtEvents) { const result = scheduleCbtEvent(event, dataset, { ...base, sittings }, config); if (result.violation) { failures.push({ eventId: event.id, title: event.title, reason: "NO_FEASIBLE_SLOT", diagnostics: { eventId: event.id, title: event.title, candidateCount: event.candidateCount, examMode: event.examMode, durationMinutes: event.durationMinutes, conflictingEvents: [], attemptedSlots: [] } }); base.hardViolations.push(result.violation); } else sittings.push(...result.sittings); }
  const totalCbt = cbtEvents.length; const cbtSittingCount = sittings.length; const batched = new Set(sittings.filter((item) => item.sequenceNumber > 1).map((item) => item.eventId)).size; const maxBatches = cbtEvents.reduce((max, event) => Math.max(max, calculateRequiredBatches(event.candidateCount, capacity(cbtVenues(dataset)))), 0); const invAssignments = sittings.flatMap((item) => item.staff).filter((item) => item.assignmentType === "TECHNICAL_SUPPORT"); const metrics = { ...base.metrics, totalEvents: dataset.events.length, scheduledEvents: base.assignments.length + totalCbt - failures.length, unscheduledEvents: base.unscheduledEvents.length + failures.length, candidateWorkload: dataset.events.reduce((sum, item) => sum + item.candidateCount, 0), penOnPaperEvents: nonCbt.length, cbtEvents: totalCbt, cbtSittings: cbtSittingCount, batchedCbtEvents: batched, maximumBatchesForEvent: maxBatches, averageBatchesPerCbtEvent: totalCbt ? cbtSittingCount / totalCbt : 0, technicalSupportAssignmentCount: invAssignments.length }; return { candidate: { ...base, sittings, unscheduledEvents: [...base.unscheduledEvents, ...failures], metrics }, previews: previewCbtBatches(dataset) };
}
