import { getConflictingEvents, getWeightedConflictDegree } from "../../exams";
import { intervalDuration, intervalsOverlap, makeInterval, minutesToTime, sortIntervals, timeToMinutes, type TimeInterval } from "../intervals";
import { packAggregateVenueCapacity } from "./allocation";
import { resolveAggregateGenerationConfig } from "./config";
import { validateAggregateTimetable } from "./validation";
import type { AggregateCalendarDay, AggregateCandidateTimetable, AggregateConstraintViolation, AggregateExamAssignment, AggregateGenerationConfig, AggregateSchedulingDataset, AggregateSlotEvaluation, AggregateTimetableMetrics, AggregateVenueAssignment, SchedulingExamEvent, UnscheduledAggregateEvent } from "./types";

type FlexibleState = { assignments: AggregateExamAssignment[]; eventIntervals: Map<string, TimeInterval>; venueIntervals: Map<string, { interval: TimeInterval; turnaround: number; allocatedCandidates: number }[]>; invigilatorIntervals: Map<string, TimeInterval[]>; dailyInvigilators: Map<string, number>; totalInvigilators: Map<string, number> };
function eventMap(dataset: AggregateSchedulingDataset) { return new Map(dataset.events.map((event) => [event.id, event])); }
const fallbackPolicy = { defaultDayStartTime: "08:00", defaultDayEndTime: "18:00", defaultTurnaroundMinutes: 30, writtenTurnaroundMinutes: 30, cbtTurnaroundMinutes: 15, timeGranularityMinutes: 30 };
function policy(dataset: AggregateSchedulingDataset) { return dataset.timePolicy ?? fallbackPolicy; }
function modeTurnaround(event: SchedulingExamEvent, dataset: AggregateSchedulingDataset, date?: string) {
  const override = date ? dataset.calendarDays?.find((day) => day.date === date)?.turnaroundMinutesOverride : null;
  return override ?? (event.examMode === "CBT" ? policy(dataset).cbtTurnaroundMinutes : policy(dataset).writtenTurnaroundMinutes);
}
function compatibleVenue(event: SchedulingExamEvent, venue: AggregateSchedulingDataset["venues"][number]) { return venue.active && (event.examMode === "CBT" ? (venue.capability === "CBT" || venue.capability === "BOTH") && (venue.usableComputerCapacity ?? 0) > 0 : (venue.capability === "WRITTEN" || venue.capability === "BOTH") && (venue.examCapacity ?? venue.capacity) > 0); }
function venueCapacity(event: SchedulingExamEvent, venue: AggregateSchedulingDataset["venues"][number]) { return event.examMode === "CBT" ? (venue.usableComputerCapacity ?? 0) : (venue.examCapacity ?? venue.capacity); }
function unavailable(interval: TimeInterval, resourceId: string, periods: AggregateSchedulingDataset["venueUnavailability"], turnaround = 0) { return periods.some((period) => { if (period.resourceId !== resourceId) return false; const start = timeToMinutes(period.startTime); const end = timeToMinutes(period.endTime); const blocked = makeInterval(period.date, start, end); if (!blocked) return false; const occupied = { ...interval, endMinutes: interval.endMinutes + turnaround }; return intervalsOverlap(occupied, blocked); }); }
function venueUsage(venueId: string, interval: TimeInterval, state: FlexibleState, turnaround: number, initial: AggregateSchedulingDataset["initialVenueUsage"] = []) { let used = 0; const blocked = (current: TimeInterval, currentTurnaround: number) => { if (intervalsOverlap(interval, current)) return "shared"; const separatedAfterCurrent = interval.startMinutes >= current.endMinutes + currentTurnaround; const separatedBeforeCurrent = current.startMinutes >= interval.endMinutes + turnaround; return separatedAfterCurrent || separatedBeforeCurrent ? null : "blocked"; }; for (const item of state.venueIntervals.get(venueId) ?? []) { const relation = blocked(item.interval, item.turnaround); if (relation === "shared") used += item.allocatedCandidates; else if (relation) return null; } for (const item of initial ?? []) { if (item.venueId !== venueId) continue; const existing = makeInterval(item.date, timeToMinutes(item.startTime), timeToMinutes(item.endTime)); if (!existing) continue; const relation = blocked(existing, item.turnaroundMinutes ?? 0); if (relation === "shared") used += item.allocatedCandidates; else if (relation) return null; } return used; }
function invigilatorFree(id: string, interval: TimeInterval, state: FlexibleState) { return !(state.invigilatorIntervals.get(id) ?? []).some((current) => intervalsOverlap(interval, current)); }

function allocateVenues(event: SchedulingExamEvent, interval: TimeInterval, state: FlexibleState, dataset: AggregateSchedulingDataset, config: AggregateGenerationConfig) {
  const turnaround = modeTurnaround(event, dataset, interval.date); const options = dataset.venues.filter((venue) => compatibleVenue(event, venue) && !unavailable(interval, venue.id, dataset.venueUnavailability, turnaround)).map((venue) => ({ venue, used: venueUsage(venue.id, interval, state, turnaround, dataset.initialVenueUsage) })).filter((item): item is { venue: typeof dataset.venues[number]; used: number } => item.used !== null);
  if (!options.length) return { success: false, assignments: [] as AggregateVenueAssignment[], reason: "VENUE_COLLISION" };
  const selected = packAggregateVenueCapacity(event.candidateCount, options.map(({ venue, used }) => ({ venueId: venue.id, code: venue.code, capacity: venueCapacity(event, venue), used })), config.venueSplitPenalty);
  return selected ? { success: true, assignments: selected, reason: undefined } : { success: false, assignments: [] as AggregateVenueAssignment[], reason: event.examMode === "CBT" ? "INSUFFICIENT_CBT_CAPACITY" : "INSUFFICIENT_VENUE_CAPACITY" };
}

function allocateInvigilators(event: SchedulingExamEvent, interval: TimeInterval, venues: AggregateVenueAssignment[], state: FlexibleState, dataset: AggregateSchedulingDataset, config: AggregateGenerationConfig) {
  const required = venues.length * config.minimumInvigilatorsPerVenue; const available = dataset.invigilators.filter((item) => item.active && invigilatorFree(item.id, interval, state) && !unavailable(interval, item.id, dataset.invigilatorUnavailability) && (item.maximumTotalAssignments == null || (state.totalInvigilators.get(item.id) ?? 0) < item.maximumTotalAssignments)).sort((a, b) => (state.dailyInvigilators.get(`${a.id}|${interval.date}`) ?? 0) - (state.dailyInvigilators.get(`${b.id}|${interval.date}`) ?? 0) || a.name.localeCompare(b.name) || a.id.localeCompare(b.id));
  if (available.length < required) return { success: false, assignments: [] as { invigilatorId: string; venueId?: string }[] };
  return { success: true, assignments: available.slice(0, required).map((item, index) => ({ invigilatorId: item.id, venueId: venues[index % venues.length]?.venueId })) };
}

function candidateStarts(day: AggregateCalendarDay, event: SchedulingExamEvent, state: FlexibleState, dataset: AggregateSchedulingDataset) {
  const start = timeToMinutes(day.startTime); const end = timeToMinutes(day.endTime); const granularity = policy(dataset).timeGranularityMinutes; const values = new Set<number>([start]); for (let value = start; value + event.durationMinutes <= end; value += granularity) values.add(value); for (const assignment of state.assignments) if (assignment.date === day.date) { const previous = timeToMinutes(assignment.endTime); const previousEvent = eventMap(dataset).get(assignment.eventId) ?? event; if (Number.isFinite(previous)) values.add(previous + modeTurnaround(previousEvent, dataset, day.date)); } return [...values].filter((value) => value >= start && value + event.durationMinutes <= end).sort((a, b) => a - b);
}

function eventOrder(dataset: AggregateSchedulingDataset, attemptSeed: number) { const compatibleCount = (event: SchedulingExamEvent) => dataset.venues.filter((venue) => compatibleVenue(event, venue)).length; const stable = (id: string) => [...id].reduce((hash, char) => (hash * 31 + char.charCodeAt(0) + attemptSeed) | 0, 7); return dataset.events.slice().sort((a, b) => getConflictingEvents(dataset.conflictGraph, b.id).filter((edge) => edge.hard).length - getConflictingEvents(dataset.conflictGraph, a.id).filter((edge) => edge.hard).length || getWeightedConflictDegree(dataset.conflictGraph, b.id) - getWeightedConflictDegree(dataset.conflictGraph, a.id) || compatibleCount(a) - compatibleCount(b) || b.candidateCount - a.candidateCount || stable(a.id) - stable(b.id) || a.id.localeCompare(b.id)); }

function evaluate(event: SchedulingExamEvent, interval: TimeInterval, state: FlexibleState, dataset: AggregateSchedulingDataset, config: AggregateGenerationConfig): AggregateSlotEvaluation {
  const hardViolations: AggregateConstraintViolation[] = []; for (const edge of getConflictingEvents(dataset.conflictGraph, event.id)) { const otherId = edge.eventAId === event.id ? edge.eventBId : edge.eventAId; const other = state.eventIntervals.get(otherId); if (other && intervalsOverlap(interval, other) && edge.hard) hardViolations.push({ code: "EVENT_CONFLICT", message: "A hard-conflicting event overlaps this interval.", metadata: { eventId: event.id, conflictingEventId: otherId, date: interval.date, startMinutes: interval.startMinutes, endMinutes: interval.endMinutes } }); }
  const venue = allocateVenues(event, interval, state, dataset, config); if (!venue.success) hardViolations.push({ code: venue.reason ?? "INSUFFICIENT_VENUE_CAPACITY", message: "No compatible venue allocation is available for this interval.", metadata: { eventId: event.id, date: interval.date, startMinutes: interval.startMinutes, endMinutes: interval.endMinutes } }); const invigilators = venue.success ? allocateInvigilators(event, interval, venue.assignments, state, dataset, config) : undefined; if (invigilators && !invigilators.success) hardViolations.push({ code: "INSUFFICIENT_INVIGILATORS", message: "No invigilator allocation is available for this interval.", metadata: { eventId: event.id, date: interval.date } }); let softPenalty = 0; for (const edge of getConflictingEvents(dataset.conflictGraph, event.id)) { const otherId = edge.eventAId === event.id ? edge.eventBId : edge.eventAId; const other = state.eventIntervals.get(otherId); if (other && intervalsOverlap(interval, other) && !edge.hard) softPenalty += config.softConflictPenalty; } if (venue.success) softPenalty += Math.max(0, venue.assignments.reduce((sum, item) => sum + item.allocatedCapacity, 0) - event.candidateCount) * config.venueWastePenaltyWeight + Math.max(0, venue.assignments.length - 1) * config.venueSplitPenalty; return { eventId: event.id, timeSlotId: `flex-${interval.date}-${interval.startMinutes}`, date: interval.date, startTime: minutesToTime(interval.startMinutes) ?? "", endTime: minutesToTime(interval.endMinutes) ?? "", feasible: hardViolations.length === 0, hardViolations, softPenalty, venuePreview: venue.success ? { success: true, venueAssignments: venue.assignments, totalCapacity: venue.assignments.reduce((sum, item) => sum + item.allocatedCapacity, 0), candidateCount: event.candidateCount, unusedCapacity: venue.assignments.reduce((sum, item) => sum + item.allocatedCapacity, 0) - event.candidateCount } : undefined, invigilatorPreview: invigilators?.success ? { success: true, invigilators: invigilators.assignments, attempted: dataset.invigilators.length } : undefined };
}

function commit(assignment: AggregateExamAssignment, state: FlexibleState, dataset: AggregateSchedulingDataset) { const interval = { date: assignment.date, startMinutes: timeToMinutes(assignment.startTime), endMinutes: timeToMinutes(assignment.endTime) }; state.assignments.push(assignment); state.eventIntervals.set(assignment.eventId, interval); const event = eventMap(dataset).get(assignment.eventId)!; for (const venue of assignment.venues) state.venueIntervals.set(venue.venueId, [...(state.venueIntervals.get(venue.venueId) ?? []), { interval, turnaround: modeTurnaround(event, dataset, assignment.date), allocatedCandidates: venue.allocatedCandidates ?? 0 }]); for (const item of assignment.invigilators) { state.invigilatorIntervals.set(item.invigilatorId, [...(state.invigilatorIntervals.get(item.invigilatorId) ?? []), interval]); state.dailyInvigilators.set(`${item.invigilatorId}|${assignment.date}`, (state.dailyInvigilators.get(`${item.invigilatorId}|${assignment.date}`) ?? 0) + 1); state.totalInvigilators.set(item.invigilatorId, (state.totalInvigilators.get(item.invigilatorId) ?? 0) + 1); } }

function attempt(dataset: AggregateSchedulingDataset, config: AggregateGenerationConfig, seed: number): AggregateCandidateTimetable { const state: FlexibleState = { assignments: [], eventIntervals: new Map(), venueIntervals: new Map(), invigilatorIntervals: new Map(), dailyInvigilators: new Map(), totalInvigilators: new Map() }; const unscheduledEvents: UnscheduledAggregateEvent[] = []; const days = (dataset.calendarDays ?? []).filter((day) => day.enabled && !day.blackoutType).sort((a, b) => a.date.localeCompare(b.date)); for (const event of eventOrder(dataset, seed)) { const evaluations: AggregateSlotEvaluation[] = []; let selected: { assignment: AggregateExamAssignment; evaluation: AggregateSlotEvaluation } | undefined; for (const day of days) for (const start of candidateStarts(day, event, state, dataset)) { const interval = makeInterval(day.date, start, start + event.durationMinutes); if (!interval) continue; const evaluation = evaluate(event, interval, state, dataset, config); evaluations.push(evaluation); if (!evaluation.feasible) continue; const assignment: AggregateExamAssignment = { eventId: event.id, timeSlotId: null, date: interval.date, startTime: evaluation.startTime!, endTime: evaluation.endTime!, venues: evaluation.venuePreview!.venueAssignments, invigilators: evaluation.invigilatorPreview!.invigilators }; if (!selected || evaluation.softPenalty < selected.evaluation.softPenalty || evaluation.softPenalty === selected.evaluation.softPenalty && `${assignment.date}|${assignment.startTime}` < `${selected.assignment.date}|${selected.assignment.startTime}`) selected = { assignment, evaluation }; } if (!selected) { unscheduledEvents.push({ eventId: event.id, title: event.title, reason: "NO_FEASIBLE_SLOT", diagnostics: { eventId: event.id, title: event.title, candidateCount: event.candidateCount, examMode: event.examMode, durationMinutes: event.durationMinutes, conflictingEvents: getConflictingEvents(dataset.conflictGraph, event.id).map((edge) => ({ eventId: edge.eventAId === event.id ? edge.eventBId : edge.eventAId, hard: edge.hard, weight: edge.weight, reasons: edge.reasons })), attemptedSlots: evaluations } }); continue; } commit(selected.assignment, state, dataset); }
  const candidate: AggregateCandidateTimetable = { assignments: state.assignments, unscheduledEvents, hardViolations: [], softScore: 0, metrics: {} as AggregateTimetableMetrics }; candidate.hardViolations = validateAggregateTimetable(candidate, dataset); candidate.metrics = flexibleMetrics(candidate, dataset); candidate.softScore = candidate.hardViolations.length * 100000 + candidate.unscheduledEvents.length * 10000 + candidate.metrics.softConflictOverlapCount * config.softConflictPenalty + candidate.metrics.totalUnusedCapacity * config.venueWastePenaltyWeight + candidate.metrics.venueSplitCount * config.venueSplitPenalty; return candidate; }

function flexibleMetrics(candidate: AggregateCandidateTimetable, dataset: AggregateSchedulingDataset): AggregateTimetableMetrics { let unused = 0; let splits = 0; let softConflictOverlapCount = 0; const inv = new Map<string, number>(); const intervals = new Map(candidate.assignments.map((assignment) => [assignment.eventId, makeInterval(assignment.date, timeToMinutes(assignment.startTime), timeToMinutes(assignment.endTime))])); for (const assignment of candidate.assignments) { const event = dataset.events.find((item) => item.id === assignment.eventId)!; unused += assignment.venues.reduce((sum, item) => sum + item.allocatedCapacity, 0) - event.candidateCount; if (assignment.venues.length > 1) splits += 1; for (const item of assignment.invigilators) inv.set(item.invigilatorId, (inv.get(item.invigilatorId) ?? 0) + 1); for (const edge of getConflictingEvents(dataset.conflictGraph, assignment.eventId)) { const otherId = edge.eventAId === assignment.eventId ? edge.eventBId : edge.eventAId; if (!edge.hard && assignment.eventId < otherId && intervals.get(otherId) && intervals.get(assignment.eventId) && intervalsOverlap(intervals.get(otherId)!, intervals.get(assignment.eventId)!)) softConflictOverlapCount += 1; } } const loads = dataset.invigilators.map((item) => inv.get(item.id) ?? 0); const avg = loads.length ? loads.reduce((sum, value) => sum + value, 0) / loads.length : 0; const variance = loads.length ? loads.reduce((sum, value) => sum + (value - avg) ** 2, 0) / loads.length : 0; return { totalEvents: dataset.events.length, scheduledEvents: candidate.assignments.length, unscheduledEvents: candidate.unscheduledEvents.length, candidateWorkload: dataset.events.reduce((sum, event) => sum + event.candidateCount, 0), penOnPaperEvents: dataset.events.filter((event) => event.examMode === "PEN_ON_PAPER").length, cbtEvents: dataset.events.filter((event) => event.examMode === "CBT").length, hardViolationCount: candidate.hardViolations.length, softConflictOverlapCount, cohortBackToBackCount: 0, cohortDailyOverloadCount: 0, averageVenueUtilization: candidate.assignments.length ? 1 - unused / candidate.assignments.reduce((sum, item) => sum + item.venues.reduce((inner, venue) => inner + venue.allocatedCapacity, 0), 0) : 0, totalUnusedCapacity: unused, cbtCapacityUtilization: 0, venueSplitCount: splits, invigilatorDailyOverloadCount: 0, invigilatorAssignmentMin: loads.length ? Math.min(...loads) : 0, invigilatorAssignmentMax: loads.length ? Math.max(...loads) : 0, invigilatorAssignmentAverage: avg, invigilatorWorkloadVariance: variance }; }

export function generateFlexibleAggregateTimetable(dataset: AggregateSchedulingDataset, inputConfig: Partial<AggregateGenerationConfig> = {}) { const config = resolveAggregateGenerationConfig(inputConfig); let best: AggregateCandidateTimetable | undefined; for (let attemptIndex = 0; attemptIndex < config.maxGenerationAttempts; attemptIndex += 1) { const candidate = attempt(dataset, config, config.seed + attemptIndex); if (!best || candidate.hardViolations.length < best.hardViolations.length || candidate.hardViolations.length === best.hardViolations.length && (candidate.unscheduledEvents.length < best.unscheduledEvents.length || candidate.unscheduledEvents.length === best.unscheduledEvents.length && candidate.softScore < best.softScore)) best = candidate; if (candidate.hardViolations.length === 0 && candidate.unscheduledEvents.length === 0) break; } return best!; }
